<?php
$healthLabels=['healthy'=>'Healthy','attention'=>'Attention Needed','at_risk'=>'At Risk'];
$usage=$client['visit_usage']; $profit=$client['profitability'];
?>
<div class="d-flex align-items-center mb-3"><a href="<?= e(url('clients')) ?>" class="btn btn-sm btn-outline-secondary mr-2"><i class="fal fa-arrow-left"></i></a><div><span class="eyebrow mb-0">CLIENT 360° PROFILE</span><div class="text-muted fs-xs">Client since <?= e(date('F Y',strtotime($client['joined_at']))) ?></div></div></div>

<section class="client-hero">
    <div class="d-flex align-items-center position-relative" style="z-index:1">
        <div class="client-avatar mr-3"><?= e(strtoupper(substr($client['business_name'],0,2))) ?></div>
        <div class="flex-1"><h1 class="mb-1 text-white fs-xxl"><?= e($client['business_name']) ?></h1><div class="opacity-70"><?= e($client['industry'] ?: 'Industry not set') ?> · <?= e($client['business_size'] ?: 'Size not classified') ?></div></div>
        <div class="d-flex align-items-center mt-2 mt-lg-0">
            <div class="client-stat"><small>Health</small><strong><i class="health-dot health-<?= e($client['health']) ?>"></i><?= e($healthLabels[$client['health']]) ?></strong></div>
            <div class="client-stat"><small>Package</small><strong><?= e($client['package_name'] ?: 'Not assigned') ?></strong></div>
            <div class="client-stat"><small>Monthly value</small><strong><?= e(money($client['monthly_price'] ?: 0)) ?></strong></div>
            <div class="client-stat"><small>Account manager</small><strong><?= e($client['account_manager'] ?: 'Unassigned') ?></strong></div>
        </div>
    </div>
</section>

<div class="kpi-grid">
    <article class="kpi-card" style="--kpi-color:#2ca879"><div class="kpi-label">Collected revenue</div><div class="kpi-value"><?= e(money($profit['revenue'])) ?></div><div class="kpi-meta">Recorded client payments</div><i class="fal fa-wallet kpi-icon"></i></article>
    <article class="kpi-card" style="--kpi-color:#e75b6c"><div class="kpi-label">Internal cost</div><div class="kpi-value"><?= e(money($profit['cost'])) ?></div><div class="kpi-meta"><?= e(number_format($profit['hours'],1)) ?> team hours</div><i class="fal fa-coins kpi-icon"></i></article>
    <article class="kpi-card" style="--kpi-color:#ff5a00"><div class="kpi-label">Actual gross profit</div><div class="kpi-value"><?= e(money($profit['profit'])) ?></div><div class="kpi-meta"><?= e(number_format($profit['margin'],1)) ?>% margin</div><i class="fal fa-chart-line kpi-icon"></i></article>
    <article class="kpi-card" style="--kpi-color:#161616"><div class="kpi-label">Visit allowance</div><div class="kpi-value"><?= $usage?e($usage['used'].' / '.$usage['included']):'—' ?></div><div class="kpi-meta"><?= $usage?e($usage['remaining'].' remaining · '.money($usage['charges']).' overages'):'No active visit allowance' ?></div><i class="fal fa-camera-retro kpi-icon"></i></article>
</div>

<ul class="nav nav-tabs nav-tabs-clean" role="tablist">
    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#overview">Overview</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#projects">Projects <span class="badge badge-soft-primary ml-1"><?= count($client['projects']) ?></span></a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tasks">Tasks <span class="badge badge-soft-primary ml-1"><?= count($client['tasks']) ?></span></a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#content">Content</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#visits">Visits</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#finance">Finance</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#activity">Activity</a></li>
</ul>

<div class="tab-content pt-3">
<div class="tab-pane fade show active" id="overview" role="tabpanel"><div class="row">
    <div class="col-lg-8">
        <section class="panel"><div class="panel-hdr"><h2>Account overview</h2><div class="panel-toolbar"><button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#modal-package"><i class="fal fa-box-open mr-1"></i> Assign package</button></div></div><div class="panel-container show"><div class="panel-content"><div class="row">
            <div class="col-md-6 mb-3"><small class="text-muted d-block">Primary contact</small><strong><?= e($client['name']) ?></strong><div><a href="mailto:<?= e($client['email']) ?>"><?= e($client['email']) ?></a></div><div><?= e($client['phone']) ?></div></div>
            <div class="col-md-6 mb-3"><small class="text-muted d-block">Business</small><strong><?= e($client['business_name']) ?></strong><div><?= e(number_format((int)$client['employee_count'])) ?> employees</div><div><?php if($client['website']): ?><a href="<?= e($client['website']) ?>" target="_blank" rel="noopener"><?= e($client['website']) ?></a><?php else: ?>Website not set<?php endif; ?></div></div>
            <div class="col-md-6"><small class="text-muted d-block">Active engagement</small><strong><?= e($client['package_name'] ?: 'No package assigned') ?></strong><div><?= $client['renewal_date']?'Renews '.e(date('M j, Y',strtotime($client['renewal_date']))):'No renewal scheduled' ?></div></div>
            <div class="col-md-6"><small class="text-muted d-block">Relationship owner</small><strong><?= e($client['account_manager'] ?: 'Unassigned') ?></strong><div>Health: <?= e($healthLabels[$client['health']]) ?></div></div>
        </div></div></div></section>
        <section class="panel"><div class="panel-hdr"><h2>Recent notes</h2><div class="panel-toolbar"><button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#modal-note">Add note</button></div></div><div class="panel-container show"><div class="panel-content">
            <?php if(!$client['notes']): ?><p class="text-muted mb-0">No notes yet.</p><?php endif; ?>
            <?php foreach($client['notes'] as $note): ?><div class="border-bottom pb-3 mb-3"><p class="mb-1"><?= nl2br(e($note['body'])) ?></p><small class="text-muted"><?= e($note['user_name']) ?> · <?= e(date('M j, Y g:i A',strtotime($note['created_at']))) ?></small></div><?php endforeach; ?>
        </div></div></section>
    </div>
    <div class="col-lg-4">
        <section class="panel"><div class="panel-hdr"><h2>Client health</h2></div><div class="panel-container show"><div class="panel-content"><form method="post" action="<?= e(url('client',['id'=>$client['id']])) ?>"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="update_health"><input type="hidden" name="client_id" value="<?= (int)$client['id'] ?>"><div class="form-group"><label>Status</label><select class="custom-select" name="health"><?php foreach($healthLabels as $id=>$label): ?><option value="<?= e($id) ?>" <?= $client['health']===$id?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Health notes</label><textarea class="form-control" name="health_notes" rows="4"><?= e($client['health_notes']) ?></textarea></div><button class="btn btn-primary btn-block">Update health</button></form></div></div></section>
        <section class="panel client-portal-access-panel"><div class="panel-hdr"><div><h2>Client portal access</h2><small><?= $client['portal_user_id']?'Login is configured':'Create a secure client login' ?></small></div><div class="panel-toolbar"><span class="badge badge-soft-<?= ($client['portal_user_status']??'inactive')==='active'?'success':'secondary' ?>"><?= e(ucfirst($client['portal_user_status']??'not configured')) ?></span></div></div><div class="panel-container show"><div class="panel-content">
            <p class="text-muted fs-sm">The client sees only their projects, task statuses, client-visible updates, calendar dates, and deliverables. Team names and internal notes stay private.</p>
            <?php if($client['portal_user_id']): ?>
                <div class="client-credential-vault mb-4">
                    <div class="d-flex align-items-center justify-content-between mb-3"><strong><i class="fal fa-user-shield mr-2"></i>Login credentials</strong><span class="badge badge-soft-primary">Protected</span></div>
                    <div class="form-group"><label>Login email</label><div class="input-group"><input class="form-control" id="client-login-email" value="<?= e($client['portal_user_email']) ?>" readonly><div class="input-group-append"><button class="btn btn-outline-secondary" type="button" data-copy-target="client-login-email" title="Copy email"><i class="fal fa-copy"></i></button></div></div></div>
                    <div class="form-group mb-2"><label>Current temporary password</label>
                        <?php if($client['portal_temporary_password']): ?>
                            <div class="input-group password-field-group"><input class="form-control" id="client-temporary-password" type="password" value="<?= e($client['portal_temporary_password']) ?>" readonly><div class="input-group-append"><button class="btn btn-outline-secondary password-visibility-toggle" type="button" data-password-toggle="client-temporary-password" aria-label="Show password"><i class="fal fa-eye"></i></button><button class="btn btn-outline-secondary" type="button" data-copy-target="client-temporary-password" title="Copy password"><i class="fal fa-copy"></i></button></div></div>
                            <small class="form-text text-muted">This temporary password remains available here until the client changes it.</small>
                        <?php else: ?>
                            <div class="credential-changed-state"><i class="fal fa-check-circle mr-2"></i>The client has changed their password, or this login predates protected credentials. Reset it below to issue a new temporary password.</div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <form method="post" action="<?= e(url('client',['id'=>$client['id']])) ?>">
                <input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="save_client_portal_access"><input type="hidden" name="client_id" value="<?= (int)$client['id'] ?>">
                <div class="form-group"><label class="required" for="portal_name">Client display name</label><input class="form-control" id="portal_name" name="name" value="<?= e($client['portal_user_name']?:$client['name']) ?>" required maxlength="120"></div>
                <div class="form-group"><label class="required" for="portal_email">Login email</label><input class="form-control" id="portal_email" type="email" name="email" value="<?= e($client['portal_user_email']?:$client['email']) ?>" required></div>
                <?php if(!$client['portal_user_id']): ?><div class="form-group"><label for="portal_password">Temporary password <span class="text-muted">(optional)</span></label><div class="input-group password-field-group"><input class="form-control" id="portal_password" type="password" name="password" minlength="10" autocomplete="new-password" placeholder="Leave blank to generate securely"><div class="input-group-append"><button class="btn btn-outline-secondary password-visibility-toggle" type="button" data-password-toggle="portal_password" aria-label="Show password"><i class="fal fa-eye"></i></button></div></div></div><?php endif; ?>
                <div class="form-group"><label class="required" for="portal_status">Access status</label><select class="custom-select" id="portal_status" name="status" required><option value="active" <?= ($client['portal_user_status']??'active')==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= ($client['portal_user_status']??'')==='inactive'?'selected':'' ?>>Inactive</option></select></div>
                <?php if(!empty($client['portal_last_login_at'])): ?><small class="text-muted d-block mb-3"><i class="fal fa-clock mr-1"></i>Last login <?= e(date('M j, Y · g:i A',strtotime($client['portal_last_login_at']))) ?></small><?php endif; ?>
                <button class="btn btn-primary btn-block"><i class="fal fa-user-lock mr-1"></i><?= $client['portal_user_id']?'Update portal access':'Create portal login' ?></button>
            </form>
            <?php if($client['portal_user_id']): ?>
                <hr class="my-4">
                <form method="post" action="<?= e(url('client',['id'=>$client['id']])) ?>">
                    <input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="reset_client_portal_password"><input type="hidden" name="client_id" value="<?= (int)$client['id'] ?>">
                    <div class="form-group"><label for="portal_reset_password">Reset temporary password</label><div class="input-group password-field-group"><input class="form-control" id="portal_reset_password" type="password" name="password" minlength="10" autocomplete="new-password" placeholder="Leave blank to generate securely"><div class="input-group-append"><button class="btn btn-outline-secondary password-visibility-toggle" type="button" data-password-toggle="portal_reset_password" aria-label="Show password"><i class="fal fa-eye"></i></button></div></div><small class="form-text text-muted">Resetting immediately replaces the client’s current login password.</small></div>
                    <button class="btn btn-outline-primary btn-block" type="submit"><i class="fal fa-redo mr-1"></i>Reset client password</button>
                </form>
            <?php endif; ?>
            <div class="portal-password-note mt-3"><i class="fal fa-info-circle mr-2"></i>Ask the client to open <strong>Change Password</strong> from the sidebar after their first login.</div>
        </div></div></section>
        <section class="panel"><div class="panel-hdr"><h2>Contacts</h2></div><div class="panel-container show"><div class="panel-content"><?php foreach($client['contacts'] as $contact): ?><div class="d-flex align-items-center mb-3"><span class="avatar-sm mr-2"><?= e(strtoupper(substr($contact['name'],0,1))) ?></span><div><strong class="d-block fs-sm"><?= e($contact['name']) ?></strong><small class="text-muted"><?= e($contact['title']) ?><?= $contact['primary_contact']?' · Primary':'' ?></small></div></div><?php endforeach; ?></div></div></section>
    </div>
</div></div>

<div class="tab-pane fade" id="projects"><section class="panel"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Project</th><th>Type</th><th>Status</th><th>Priority</th><th>Deadline</th><th>Hours</th><th>Budget</th></tr></thead><tbody><?php foreach($client['projects'] as $project): ?><tr><td><strong><?= e($project['name']) ?></strong></td><td><?= e($project['project_type']) ?></td><td><span class="badge badge-soft-primary"><?= e($project['status']) ?></span></td><td><?= e($project['priority']) ?></td><td><?= e($project['deadline']?date('M j, Y',strtotime($project['deadline'])):'—') ?></td><td><?= e($project['actual_hours'].' / '.$project['estimated_hours']) ?></td><td><?= e(money($project['budget'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<div class="tab-pane fade" id="tasks"><section class="panel"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Task</th><th>Assignee</th><th>Status</th><th>Priority</th><th>Due</th><th>Hours</th></tr></thead><tbody><?php foreach($client['tasks'] as $task): ?><tr><td><strong><?= e($task['title']) ?></strong></td><td><?= e($task['assignee'] ?: 'Unassigned') ?></td><td><span class="badge badge-soft-primary"><?= e(str_replace('_',' ',$task['status'])) ?></span></td><td><?= e($task['priority']) ?></td><td><?= e($task['due_date']?date('M j',strtotime($task['due_date'])):'—') ?></td><td><?= e($task['actual_hours'].' / '.$task['estimated_hours']) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<div class="tab-pane fade" id="content"><section class="panel"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Content</th><th>Platform</th><th>Format</th><th>Status</th><th>Approval</th><th>Scheduled</th></tr></thead><tbody><?php foreach($client['content'] as $item): ?><tr><td><strong><?= e($item['title']) ?></strong></td><td><?= e($item['platform']) ?></td><td><?= e($item['content_type']) ?></td><td><span class="badge badge-soft-primary"><?= e(str_replace('_',' ',$item['status'])) ?></span></td><td><?= e(str_replace('_',' ',$item['approval_status'])) ?></td><td><?= e($item['scheduled_at']?date('M j, g:i A',strtotime($item['scheduled_at'])):'—') ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<div class="tab-pane fade" id="visits"><section class="panel"><div class="panel-hdr"><h2>Content production usage</h2><div class="panel-toolbar"><?php if($usage): ?><span class="badge badge-soft-success"><?= (int)$usage['remaining'] ?> visits remaining this month</span><?php endif; ?></div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Type</th><th>Purpose</th><th>Producer</th><th>Status</th><th>Billing</th></tr></thead><tbody><?php foreach($client['visits'] as $visit): ?><tr><td><?= e(date('M j, Y',strtotime($visit['visit_date']))) ?></td><td><?= e($visit['visit_type']) ?></td><td><?= e($visit['purpose']) ?></td><td><?= e($visit['assignee'] ?: 'Unassigned') ?></td><td><span class="badge badge-soft-primary"><?= e($visit['status']) ?></span></td><td><?= $visit['is_additional']?'<span class="text-warning font-weight-bold">'.e(money($visit['additional_charge'])).' overage</span>':'Included' ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<div class="tab-pane fade" id="finance"><section class="panel"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Invoice</th><th>Issued</th><th>Due</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($client['invoices'] as $invoice): ?><tr><td><strong><?= e($invoice['invoice_number']) ?></strong></td><td><?= e(date('M j, Y',strtotime($invoice['issue_date']))) ?></td><td><?= e(date('M j, Y',strtotime($invoice['due_date']))) ?></td><td><?= e(money($invoice['total'])) ?></td><td><?= e(money($invoice['amount_paid'])) ?></td><td><?= e(money($invoice['total']-$invoice['amount_paid'])) ?></td><td><span class="badge badge-soft-primary"><?= e(str_replace('_',' ',$invoice['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<div class="tab-pane fade" id="activity"><section class="panel"><div class="panel-hdr"><h2>Relationship timeline</h2></div><div class="panel-container show"><div class="panel-content"><div class="activity-timeline"><?php foreach($client['activities'] as $activity): ?><div class="timeline-item"><p><strong><?= e($activity['description']) ?></strong></p><small><?= e(date('M j, Y · g:i A',strtotime($activity['created_at']))) ?><?= $activity['user_name']?' · '.e($activity['user_name']):'' ?></small></div><?php endforeach; ?></div></div></div></section></div>
</div>

<div class="modal fade" id="modal-note" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" action="<?= e(url('client',['id'=>$client['id']])) ?>"><div class="modal-header"><h2 class="modal-title fs-xl">Add client note</h2><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="add_note"><input type="hidden" name="client_id" value="<?= (int)$client['id'] ?>"><textarea class="form-control" name="body" rows="6" required placeholder="Add useful relationship context…"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Save note</button></div></form></div></div></div>

<div class="modal fade" id="modal-package" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" action="<?= e(url('client',['id'=>$client['id']])) ?>"><div class="modal-header"><h2 class="modal-title fs-xl">Assign a package</h2><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="assign_package"><input type="hidden" name="client_id" value="<?= (int)$client['id'] ?>"><div class="form-group"><label class="required">Package</label><select class="custom-select" name="package_id" required><option value="">Select package</option><?php foreach($options['packages'] as $package): ?><option value="<?= (int)$package['id'] ?>"><?= e($package['name']) ?><?= $package['price']?' · '.e(money($package['price'])):'' ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Custom agreed price</label><input class="form-control" type="number" name="custom_price" min="0" step="0.01" placeholder="Leave blank to use package price"></div><div class="form-group"><label class="required">Start date</label><input class="form-control" type="date" name="start_date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="form-group"><label>Renewal date</label><input class="form-control" type="date" name="renewal_date" value="<?= e(date('Y-m-d',strtotime('+1 year'))) ?>"></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Assign package</button></div></form></div></div></div>
