<?php
$problems=['Website outdated','Poor branding','Poor Google presence','Low reviews','Poor social media','Low engagement','No content','No video','No photography','Poor SEO','Low leads','Poor conversion','Other'];
$outcomes=['More leads','More calls','More appointments','More sales','More reviews','Better branding','Better website','Better social media','More content','Better Google presence','Business expansion','New location','New services'];
?>
<div class="page-title-wrap"><div><span class="eyebrow">CRM INTELLIGENCE</span><h1>Discovery & Consultation</h1><p>Capture the business context required to recommend the right scope—not just a list of services.</p></div><button class="btn btn-primary" data-toggle="modal" data-target="#modal-add"><i class="fal fa-comments-alt mr-1"></i> New discovery</button></div>
<section class="panel"><div class="panel-container show"><div class="panel-content"><div class="data-toolbar"><div class="input-group table-search"><div class="input-group-prepend"><span class="input-group-text bg-white"><i class="fal fa-search"></i></span></div><input class="form-control" data-table-search placeholder="Search consultations…"></div><span class="text-muted fs-sm"><?= count($rows) ?> completed sessions</span></div><div class="table-responsive"><table class="table mb-0" data-agency-table><thead><tr><th>Business</th><th>Contact</th><th>Main goal</th><th>Current problems</th><th>Desired outcomes</th><th>Completed by</th><th>Date</th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr data-table-row><td><strong><?= e($row['business_name']) ?></strong><div class="mt-2"><button type="button" class="btn btn-xs btn-outline-primary text-nowrap" data-toggle="modal" data-target="#consultation-<?= (int)$row['id'] ?>"><i class="fal fa-eye mr-1"></i> View details</button></div></td><td><?= e($row['contact_name']) ?></td><td><?= e($row['business_goals_data']['main_goal']??'—') ?></td><td><div class="text-truncate" style="max-width:220px" title="<?= e(implode(', ',$row['problems_data'])) ?>"><?= e(implode(', ',$row['problems_data']) ?: '—') ?></div></td><td><div class="text-truncate" style="max-width:220px" title="<?= e(implode(', ',$row['outcomes_data'])) ?>"><?= e(implode(', ',$row['outcomes_data']) ?: '—') ?></div></td><td><?= e($row['completed_by_name'] ?: 'System user') ?></td><td><?= $row['completed_at']?e(date('M j, Y',strtotime($row['completed_at']))):'—' ?></td></tr><?php endforeach; ?>
<?php if(!$rows): ?><tr><td colspan="7"><div class="empty-state"><i class="fal fa-comments-alt"></i><h3>No consultations saved</h3><p class="text-muted">Complete a structured discovery to improve scoping and proposals.</p></div></td></tr><?php endif; ?>
</tbody></table></div></div></div></section>

<?php foreach($rows as $consultation): $discoveryContext=['business_name'=>$consultation['business_name'],'contact_name'=>$consultation['contact_name']]; ?>
<div class="modal fade" id="consultation-<?= (int)$consultation['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="consultation-title-<?= (int)$consultation['id'] ?>" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document"><div class="modal-content">
    <div class="modal-header"><div><span class="eyebrow mb-1">COMPLETE DISCOVERY RECORD</span><h2 class="modal-title" id="consultation-title-<?= (int)$consultation['id'] ?>"><?= e($consultation['business_name']) ?></h2><div class="text-muted fs-sm mt-1"><?= e($consultation['business_goals_data']['main_goal']??'Discovery consultation') ?></div></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div>
    <div class="modal-body"><?php include resource_path('views/agency/partials/discovery-details.blade.php'); ?></div>
    <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button></div>
</div></div></div>
<?php endforeach; unset($discoveryContext); ?>

<div class="modal fade" id="modal-add" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="post" action="<?= e(url('discovery')) ?>"><div class="modal-header"><div><span class="eyebrow mb-1">STRUCTURED DISCOVERY</span><h2 class="modal-title fs-xl">Client consultation</h2></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="create_consultation">
<div class="alert alert-info"><i class="fal fa-info-circle mr-2"></i>Select either an unconverted lead or an existing client.</div>
<h3 class="fs-lg border-bottom pb-2">Relationship</h3><div class="row"><div class="col-md-6"><div class="form-group"><label>Lead</label><select class="custom-select" name="lead_id"><option value="">Not a lead</option><?php foreach($options['leads'] as $lead): ?><option value="<?= (int)$lead['id'] ?>" <?= (int)($selectedLeadId??0)===(int)$lead['id']?'selected':'' ?>><?= e($lead['name']) ?></option><?php endforeach; ?></select></div></div><div class="col-md-6"><div class="form-group"><label>Existing client</label><select class="custom-select" name="client_id"><option value="">Not an existing client</option><?php foreach($options['clients'] as $client): ?><option value="<?= (int)$client['id'] ?>"><?= e($client['name']) ?></option><?php endforeach; ?></select></div></div></div>
<h3 class="fs-lg border-bottom pb-2 mt-2">Business goals</h3><div class="row"><div class="col-md-6"><div class="form-group"><label>Main business goal</label><input class="form-control" name="main_goal"></div></div><div class="col-md-3"><div class="form-group"><label>Revenue goal</label><input class="form-control" name="revenue_goal"></div></div><div class="col-md-3"><div class="form-group"><label>Customer acquisition goal</label><input class="form-control" name="acquisition_goal"></div></div><div class="col-md-6"><div class="form-group"><label>Expansion plans</label><textarea class="form-control" name="expansion_plans" rows="2"></textarea></div></div><div class="col-md-3"><div class="form-group"><label>Main challenges</label><textarea class="form-control" name="challenges" rows="2"></textarea></div></div><div class="col-md-3"><div class="form-group"><label>Main competitors</label><textarea class="form-control" name="competitors" rows="2"></textarea></div></div></div>
<h3 class="fs-lg border-bottom pb-2 mt-2">Marketing snapshot</h3><div class="row"><div class="col-md-4"><div class="form-group"><label>Current website</label><input class="form-control" name="current_website"></div></div><div class="col-md-4"><div class="form-group"><label>Current social media</label><input class="form-control" name="current_social_media"></div></div><div class="col-md-4"><div class="form-group"><label>Google Business Profile</label><input class="form-control" name="google_business"></div></div><div class="col-md-4"><div class="form-group"><label>Current advertising</label><input class="form-control" name="current_advertising"></div></div><div class="col-md-4"><div class="form-group"><label>SEO status</label><input class="form-control" name="seo_status"></div></div><div class="col-md-4"><div class="form-group"><label>Marketing budget</label><input class="form-control" name="marketing_budget"></div></div><div class="col-12"><div class="form-group"><label>Previous agency experience</label><textarea class="form-control" name="agency_experience" rows="2"></textarea></div></div></div>
<h3 class="fs-lg border-bottom pb-2 mt-2">Target customer</h3><div class="row"><div class="col-md-4"><div class="form-group"><label>Target customer</label><textarea class="form-control" name="target_customer" rows="2"></textarea></div></div><div class="col-md-4"><div class="form-group"><label>Geographic market</label><textarea class="form-control" name="geographic_market" rows="2"></textarea></div></div><div class="col-md-4"><div class="form-group"><label>Demographics</label><textarea class="form-control" name="customer_demographics" rows="2"></textarea></div></div><div class="col-md-6"><div class="form-group"><label>Customer problems</label><textarea class="form-control" name="customer_problems" rows="2"></textarea></div></div><div class="col-md-6"><div class="form-group"><label>Why customers choose them</label><textarea class="form-control" name="why_customers_choose" rows="2"></textarea></div></div></div>
<div class="row"><div class="col-lg-6"><h3 class="fs-lg border-bottom pb-2">Current problems</h3><div class="row"><?php foreach($problems as $i=>$problem): ?><div class="col-md-6"><div class="custom-control custom-checkbox mb-2"><input class="custom-control-input" type="checkbox" id="problem_<?= $i ?>" name="current_problems[]" value="<?= e($problem) ?>"><label class="custom-control-label" for="problem_<?= $i ?>"><?= e($problem) ?></label></div></div><?php endforeach; ?></div></div><div class="col-lg-6"><h3 class="fs-lg border-bottom pb-2">Desired outcomes</h3><div class="row"><?php foreach($outcomes as $i=>$outcome): ?><div class="col-md-6"><div class="custom-control custom-checkbox mb-2"><input class="custom-control-input" type="checkbox" id="outcome_<?= $i ?>" name="desired_outcomes[]" value="<?= e($outcome) ?>"><label class="custom-control-label" for="outcome_<?= $i ?>"><?= e($outcome) ?></label></div></div><?php endforeach; ?></div></div></div>
<div class="form-group mt-3"><label>Consultation notes</label><textarea class="form-control" name="notes" rows="4"></textarea></div>
</div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save discovery</button></div></form></div></div></div>
