<?php
$profile=$invoice['profile'];$bank=$invoice['bank_account'];$balance=max(0,(float)$invoice['amount_due']);
$logoPath=public_path('assets/img/360-logo-final-exact.png');
$logoSrc=is_file($logoPath)?'data:image/png;base64,'.base64_encode((string)file_get_contents($logoPath)):'';
$signatureSrc='';
if(!empty($profile['signature_path'])){$signaturePath=storage_path('app/private/invoice-signatures/'.$profile['signature_path']);if(is_file($signaturePath)){$extension=strtolower(pathinfo($signaturePath,PATHINFO_EXTENSION));$mime=$extension==='png'?'image/png':($extension==='webp'?'image/webp':'image/jpeg');$signatureSrc='data:'.$mime.';base64,'.base64_encode((string)file_get_contents($signaturePath));}}
$agencyAddress=array_values(array_filter([$profile['address_line_1']??null,$profile['address_line_2']??null,trim(implode(', ',array_filter([$profile['city']??null,$profile['province']??null,$profile['postal_code']??null]))),$profile['country']??null]));
?>
<article class="invoice-document">
    <header class="invoice-doc-header"><div><?php if($logoSrc): ?><img src="<?= e($logoSrc) ?>" alt="360 Creative Agency"><?php else: ?><strong>360</strong><?php endif; ?></div><div><span>INVOICE</span><h1><?= e($invoice['invoice_number']) ?></h1><small><?= e(strtoupper((string)($invoice['status']??'sent'))) ?></small></div></header>
    <section class="invoice-parties"><div><span>FROM</span><h2><?= e($profile['agency_name']) ?></h2><?php foreach($agencyAddress as $line): ?><p><?= e($line) ?></p><?php endforeach; ?><?php if(!empty($profile['email'])): ?><p><?= e($profile['email']) ?></p><?php endif; ?><?php if(!empty($profile['phone'])): ?><p><?= e($profile['phone']) ?></p><?php endif; ?><?php if(!empty($profile['tax_number'])): ?><p><strong>Tax / HST:</strong> <?= e($profile['tax_number']) ?></p><?php endif; ?><?php if(!empty($profile['ocn_bin'])): ?><p><strong>Number (OCN/BIN):</strong> <?= e($profile['ocn_bin']) ?></p><?php endif; ?></div><div><span>BILL TO</span><h2><?= e($invoice['business_name']) ?></h2><p><?= e($invoice['contact_name']) ?></p><p><?= e($invoice['client_email']) ?></p><?php if(!empty($invoice['client_phone'])): ?><p><?= e($invoice['client_phone']) ?></p><?php endif; ?><?php if(!empty($invoice['project_name'])): ?><p><strong>Project:</strong> <?= e($invoice['project_name']) ?></p><?php endif; ?></div><div class="invoice-meta"><dl><dt>Issued</dt><dd><?= e(date('F j, Y',strtotime($invoice['issue_date']))) ?></dd><dt>Due</dt><dd><?= e(date('F j, Y',strtotime($invoice['due_date']))) ?></dd><dt>Currency</dt><dd><?= e($invoice['currency']??'CAD') ?></dd><?php if(!empty($invoice['purchase_order_number'])): ?><dt>PO / reference</dt><dd><?= e($invoice['purchase_order_number']) ?></dd><?php endif; ?></dl></div></section>
    <?php if(!empty($invoice['milestone_title'])||!empty($invoice['milestone_description'])): ?><section class="invoice-milestone"><span>PAYMENT MILESTONE</span><h3><?= e($invoice['milestone_title']?:'Project milestone') ?></h3><?php if(!empty($invoice['milestone_description'])): ?><p><?= nl2br(e($invoice['milestone_description'])) ?></p><?php endif; ?></section><?php endif; ?>
    <table class="invoice-items"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody><?php foreach($invoice['items'] as $item): ?><tr><td><?= nl2br(e($item['description'])) ?></td><td><?= e(rtrim(rtrim(number_format((float)$item['quantity'],2),'0'),'.')) ?></td><td><?= e(money($item['unit_price'])) ?></td><td><?= e(money($item['total'])) ?></td></tr><?php endforeach; ?></tbody></table>
    <div class="invoice-bottom"><section><?php if($bank): ?><div class="invoice-bank"><span>PAYMENT DETAILS</span><h3><?= e($bank['account_name']) ?></h3><p><strong><?= e($bank['bank_name']) ?></strong></p><?php if(!empty($bank['account_holder'])): ?><p>Account holder: <?= e($bank['account_holder']) ?></p><?php endif; ?><?php if(!empty($bank['account_number'])): ?><p>Account number: <?= e($bank['account_number']) ?></p><?php endif; ?><?php if(!empty($bank['transit_number'])): ?><p>Transit: <?= e($bank['transit_number']) ?></p><?php endif; ?><?php if(!empty($bank['institution_number'])): ?><p>Institution: <?= e($bank['institution_number']) ?></p><?php endif; ?><?php if(!empty($bank['swift_code'])): ?><p>SWIFT: <?= e($bank['swift_code']) ?></p><?php endif; ?><?php if(!empty($bank['iban'])): ?><p>IBAN: <?= e($bank['iban']) ?></p><?php endif; ?><?php if(!empty($bank['payment_instructions'])): ?><p class="invoice-instructions"><?= nl2br(e($bank['payment_instructions'])) ?></p><?php endif; ?></div><?php endif; ?><?php if(!empty($invoice['payment_terms'])): ?><div class="invoice-terms"><span>PAYMENT TERMS</span><p><?= nl2br(e($invoice['payment_terms'])) ?></p></div><?php endif; ?></section><aside class="invoice-totals"><dl><dt>Subtotal</dt><dd><?= e(money($invoice['subtotal'])) ?></dd><?php if((float)$invoice['discount']>0): ?><dt>Discount</dt><dd>−<?= e(money($invoice['discount'])) ?></dd><?php endif; ?><dt>Tax</dt><dd><?= e(money($invoice['tax'])) ?></dd><dt class="grand">Original invoice total</dt><dd class="grand"><?= e(money($invoice['total'])) ?></dd><?php if((float)($invoice['adjustment_total']??0)>0): ?><dt>Credits / cancellations</dt><dd>−<?= e(money($invoice['adjustment_total'])) ?></dd><dt>Net invoice value</dt><dd><?= e(money($invoice['adjusted_total'])) ?></dd><?php endif; ?><dt>Paid</dt><dd>−<?= e(money($invoice['amount_paid'])) ?></dd><dt class="balance">Balance due</dt><dd class="balance"><?= e(money($balance)) ?></dd></dl></aside></div>
    <?php if(!empty($invoice['notes'])): ?><section class="invoice-note"><span>NOTES</span><p><?= nl2br(e($invoice['notes'])) ?></p></section><?php endif; ?>
    <footer class="invoice-signature"><div><?php if($signatureSrc): ?><img src="<?= e($signatureSrc) ?>" alt="Authorized signature"><?php endif; ?><span class="signature-line"></span><strong><?= e($profile['authorized_signatory_name']?:'Authorized signature') ?></strong><?php if(!empty($profile['authorized_signatory_title'])): ?><small><?= e($profile['authorized_signatory_title']) ?></small><?php endif; ?></div><p>Thank you for choosing <?= e($profile['agency_name']) ?>.</p></footer>
</article>
