<?php
$profile=$adjustment['profile'];
$isCancellation=$adjustment['type']==='cancellation';
$documentTitle=$isCancellation?'INVOICE CANCELLATION CERTIFICATE':'CREDIT NOTE / PARTIAL REFUND';
$logoPath=public_path('assets/img/360-logo-final-exact.png');
$logoSrc=is_file($logoPath)?'data:image/png;base64,'.base64_encode((string)file_get_contents($logoPath)):'';
$signatureSrc='';
if(!empty($profile['signature_path'])){$signaturePath=storage_path('app/private/invoice-signatures/'.$profile['signature_path']);if(is_file($signaturePath)){$extension=strtolower(pathinfo($signaturePath,PATHINFO_EXTENSION));$mime=$extension==='png'?'image/png':($extension==='webp'?'image/webp':'image/jpeg');$signatureSrc='data:'.$mime.';base64,'.base64_encode((string)file_get_contents($signaturePath));}}
$agencyAddress=array_values(array_filter([$profile['address_line_1']??null,$profile['address_line_2']??null,trim(implode(', ',array_filter([$profile['city']??null,$profile['province']??null,$profile['postal_code']??null]))),$profile['country']??null]));
?>
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:28px 34px}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,Arial,sans-serif;color:#22201e;font-size:10px}.doc{border:1px solid #e4dfda}.head{display:table;width:100%;padding:24px 28px;background:#0b0b0b;color:#fff}.head>div{display:table-cell;vertical-align:middle}.head>div:last-child{text-align:right}.head img{width:98px}.head span,.label{color:#ff5a14;font-size:8px;font-weight:bold;letter-spacing:1.2px}.head h1{margin:5px 0 3px;font-size:17px}.head small{color:#d8d4d1}.parties{display:table;width:100%;padding:24px 28px;border-bottom:1px solid #ece8e4}.parties>div{display:table-cell;width:33%;vertical-align:top}.parties h2{margin:7px 0;font-size:13px}.parties p{margin:3px 0;color:#68625e}.meta dl{margin:0}.meta dt,.meta dd{display:inline-block;width:48%;margin:0 0 7px}.meta dt{color:#777}.meta dd{text-align:right;font-weight:bold}.notice{margin:22px 28px;padding:16px 18px;border-left:4px solid #ff5a14;background:#fff3ed}.notice h3{margin:5px 0;font-size:13px}.notice p{margin:5px 0 0;color:#5e5752;line-height:1.55}.items{width:calc(100% - 56px);margin:20px 28px;border-collapse:collapse}.items th{padding:10px 9px;border-bottom:2px solid #151515;text-align:left;font-size:8px;letter-spacing:.7px}.items td{padding:12px 9px;border-bottom:1px solid #e7e2de}.items th:last-child,.items td:last-child{text-align:right}.summary{width:44%;margin:8px 28px 18px auto;padding:14px 16px;background:#f6f3f1}.summary dl{margin:0}.summary dt,.summary dd{display:inline-block;width:49%;margin:0;padding:6px 0}.summary dd{text-align:right;font-weight:bold}.summary .total{padding-top:10px;border-top:1px solid #aaa;color:#d94708;font-size:12px}.reference{margin:0 28px 18px;padding:12px 14px;background:#faf9f7}.reference p{margin:5px 0;color:#625e5a}.signature{display:table;width:100%;padding:16px 28px 24px}.signature>div,.signature>p{display:table-cell;width:50%;vertical-align:bottom}.signature>p{text-align:right;color:#777}.signature img{display:block;max-width:130px;max-height:50px}.line{display:block;width:165px;margin:5px 0;border-top:1px solid #777}.signature strong,.signature small{display:block}.foot{padding:11px 28px;background:#0b0b0b;color:#ccc;text-align:center;font-size:8px}
</style></head><body><article class="doc">
<header class="head"><div><?php if($logoSrc): ?><img src="<?= e($logoSrc) ?>" alt="360 Creative Agency"><?php else: ?><strong>360</strong><?php endif; ?></div><div><span><?= e($documentTitle) ?></span><h1><?= e($adjustment['adjustment_number']) ?></h1><small>Issued against <?= e($adjustment['invoice_number']) ?></small></div></header>
<section class="parties"><div><span class="label">ISSUED BY</span><h2><?= e($profile['agency_name']) ?></h2><?php foreach($agencyAddress as $line): ?><p><?= e($line) ?></p><?php endforeach; ?><?php if(!empty($profile['email'])): ?><p><?= e($profile['email']) ?></p><?php endif; ?><?php if(!empty($profile['tax_number'])): ?><p><strong>Tax / HST:</strong> <?= e($profile['tax_number']) ?></p><?php endif; ?><?php if(!empty($profile['ocn_bin'])): ?><p><strong>Number (OCN/BIN):</strong> <?= e($profile['ocn_bin']) ?></p><?php endif; ?></div><div><span class="label">ISSUED TO</span><h2><?= e($adjustment['business_name']) ?></h2><p><?= e($adjustment['contact_name']) ?></p><p><?= e($adjustment['client_email']) ?></p><?php if(!empty($adjustment['project_name'])): ?><p><strong>Project:</strong> <?= e($adjustment['project_name']) ?></p><?php endif; ?></div><div class="meta"><dl><dt>Adjustment date</dt><dd><?= e(date('F j, Y',strtotime($adjustment['adjustment_date']))) ?></dd><dt>Original invoice</dt><dd><?= e($adjustment['invoice_number']) ?></dd><dt>Invoice issued</dt><dd><?= e(date('F j, Y',strtotime($adjustment['issue_date']))) ?></dd><dt>Currency</dt><dd><?= e($adjustment['currency']??'CAD') ?></dd></dl></div></section>
<section class="notice"><span class="label"><?= $isCancellation?'CANCELLATION CONFIRMATION':'CREDIT CONFIRMATION' ?></span><h3><?= $isCancellation?'The original invoice has been cancelled in full.':'A partial refund / account credit has been recorded.' ?></h3><p><?= e($adjustment['reason']) ?></p></section>
<table class="items"><thead><tr><th>Description</th><th>Subtotal</th><th>Tax</th><th>Adjustment total</th></tr></thead><tbody><tr><td><?= e($isCancellation?'Full cancellation of invoice '.$adjustment['invoice_number']:'Partial refund / credit against invoice '.$adjustment['invoice_number']) ?></td><td><?= e(money($adjustment['subtotal'])) ?></td><td><?= e(money($adjustment['tax'])) ?></td><td>−<?= e(money($adjustment['total'])) ?></td></tr></tbody></table>
<aside class="summary"><dl><dt>Original invoice</dt><dd><?= e(money($adjustment['invoice_total'])) ?></dd><dt>Adjustment subtotal</dt><dd>−<?= e(money($adjustment['subtotal'])) ?></dd><dt>Tax reversed</dt><dd>−<?= e(money($adjustment['tax'])) ?></dd><dt class="total"><?= $isCancellation?'Total cancelled':'Total credited' ?></dt><dd class="total">−<?= e(money($adjustment['total'])) ?></dd></dl></aside>
<?php if(!empty($adjustment['method'])||!empty($adjustment['reference'])): ?><section class="reference"><span class="label">REVERSAL DETAILS</span><?php if(!empty($adjustment['method'])): ?><p><strong>Method:</strong> <?= e($adjustment['method']) ?></p><?php endif; ?><?php if(!empty($adjustment['reference'])): ?><p><strong>Reference:</strong> <?= e($adjustment['reference']) ?></p><?php endif; ?></section><?php endif; ?>
<footer class="signature"><div><?php if($signatureSrc): ?><img src="<?= e($signatureSrc) ?>" alt="Authorized signature"><?php endif; ?><span class="line"></span><strong><?= e($profile['authorized_signatory_name']?:'Authorized representative') ?></strong><small><?= e($profile['authorized_signatory_title']?:$profile['agency_name']) ?></small></div><p>Issued by <?= e($adjustment['created_by_name']?:$profile['agency_name']) ?></p></footer><div class="foot">This document forms part of the permanent accounting history for invoice <?= e($adjustment['invoice_number']) ?>.</div>
</article></body></html>
