<?php
$effectiveTaxBase=max(0,(float)$invoice['subtotal']-(float)$invoice['discount']);
$effectiveTaxRate=$effectiveTaxBase>0?round((float)$invoice['tax']/$effectiveTaxBase*100,2):0;
$canAdjust=!in_array($invoice['status'],['draft','cancelled','refunded'],true);
$remainingAdjustment=max(0,(float)$invoice['total']-(float)$invoice['adjustment_total']);
?>
<div class="page-title-wrap invoice-detail-heading"><div><span class="eyebrow">INVOICE DETAIL</span><h1><?= e($invoice['invoice_number']) ?></h1><p><?= e($invoice['business_name']) ?><?= !empty($invoice['project_name'])?' · '.e($invoice['project_name']):'' ?></p></div><div class="invoice-detail-actions"><a class="btn btn-outline-secondary" href="<?= e(url('invoices')) ?>"><i class="fal fa-arrow-left mr-1"></i>Invoices</a><button class="btn btn-outline-primary" type="button" onclick="window.print()"><i class="fal fa-print mr-1"></i>Print</button><a class="btn btn-primary" href="<?= e(agency_url('invoice_pdf',['id'=>(int)$invoice['id']])) ?>"><i class="fal fa-file-pdf mr-1"></i>Invoice PDF</a><?php if($canAdjust): ?><button class="btn btn-outline-warning" type="button" data-toggle="modal" data-target="#modal-partial-refund"><i class="fal fa-undo-alt mr-1"></i>Partial refund</button><?php if(empty($invoice['adjustments'])): ?><button class="btn btn-outline-danger" type="button" data-toggle="modal" data-target="#modal-cancel-invoice"><i class="fal fa-ban mr-1"></i>Cancel invoice</button><?php endif; ?><?php endif; ?></div></div>

<?php if((float)$invoice['adjustment_total']>0): ?><section class="invoice-adjustment-banner <?= $invoice['status']==='cancelled'?'is-cancelled':'is-refunded' ?>"><div><i class="fal fa-<?= $invoice['status']==='cancelled'?'ban':'undo-alt' ?>"></i><span><strong><?= e(ucwords(str_replace('_',' ',$invoice['status']))) ?></strong><small><?= count($invoice['adjustments']) ?> adjustment document<?= count($invoice['adjustments'])===1?'':'s' ?> issued against this invoice</small></span></div><div><small>Original <?= e(money($invoice['total'])) ?></small><strong>Net <?= e(money($invoice['adjusted_total'])) ?></strong></div></section><?php endif; ?>

<div class="invoice-screen-document">@include('agency.invoice-document')</div>

<?php if(!empty($invoice['adjustments'])): ?><section class="panel mt-3"><div class="panel-hdr"><div><h2>Credit notes & cancellation documents</h2><small>Every reversal remains attached to the original invoice</small></div></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Document</th><th>Type</th><th>Date</th><th>Reason</th><th>Method / reference</th><th>Subtotal</th><th>Tax</th><th>Total</th><th class="text-right">PDF</th></tr></thead><tbody><?php foreach($invoice['adjustments'] as $adjustment): ?><tr><td><strong><?= e($adjustment['adjustment_number']) ?></strong></td><td><span class="badge badge-soft-<?= $adjustment['type']==='cancellation'?'danger':'warning' ?>"><?= $adjustment['type']==='cancellation'?'Cancellation':'Partial refund' ?></span></td><td><?= e(date('M j, Y',strtotime($adjustment['adjustment_date']))) ?></td><td><?= e($adjustment['reason']) ?></td><td><?= e(implode(' · ',array_filter([$adjustment['method'],$adjustment['reference']]))?:'—') ?></td><td><?= e(money($adjustment['subtotal'])) ?></td><td><?= e(money($adjustment['tax'])) ?></td><td class="text-danger font-weight-bold">−<?= e(money($adjustment['total'])) ?></td><td class="text-right"><a class="btn btn-sm btn-outline-primary" href="<?= e(agency_url('invoice_adjustment_pdf',['id'=>(int)$adjustment['id']])) ?>"><i class="fal fa-file-pdf mr-1"></i>Download</a></td></tr><?php endforeach; ?></tbody></table></div></div></section><?php endif; ?>

<?php if(!empty($invoice['payments'])): ?><section class="panel mt-3"><div class="panel-hdr"><h2>Payment history</h2></div><div class="panel-container show"><div class="panel-content"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Recorded by</th></tr></thead><tbody><?php foreach($invoice['payments'] as $payment): ?><tr><td><?= e(date('M j, Y',strtotime($payment['payment_date']))) ?></td><td><strong><?= e(money($payment['amount'])) ?></strong></td><td><?= e($payment['method']) ?></td><td><?= e($payment['reference']?:'—') ?></td><td><?= e($payment['recorded_by_name']?:'System') ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></section><?php endif; ?>

<?php if($canAdjust): ?>
<div class="modal fade" id="modal-partial-refund" tabindex="-1" role="dialog" aria-labelledby="partial-refund-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="post" action="<?= e(url('invoice',['id'=>(int)$invoice['id']])) ?>"><div class="modal-header"><div><span class="eyebrow">CREDIT NOTE</span><h2 class="modal-title fs-xl" id="partial-refund-title">Record a partial refund</h2><p class="mb-0 text-muted">Creates a numbered PDF credit note without altering the original invoice.</p></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="create_invoice_adjustment"><input type="hidden" name="invoice_id" value="<?= (int)$invoice['id'] ?>"><input type="hidden" name="adjustment_type" value="partial_refund"><div class="alert alert-info border-0"><strong><?= e(money($remainingAdjustment)) ?></strong> remains available for credit on this invoice.</div><div class="row"><div class="col-md-6"><div class="form-group"><label class="required">Refund subtotal</label><input class="form-control" type="number" min="0.01" step="0.01" name="amount" required></div></div><div class="col-md-6"><div class="form-group"><label>Tax applied to refund %</label><input class="form-control" type="number" min="0" max="100" step="0.01" name="tax_percent" value="<?= e((string)$effectiveTaxRate) ?>"></div></div><div class="col-md-6"><div class="form-group"><label class="required">Adjustment date</label><input class="form-control" type="date" name="adjustment_date" value="<?= e(date('Y-m-d')) ?>" required></div></div><div class="col-md-6"><div class="form-group"><label>Refund method</label><select class="custom-select" name="method"><option value="">Not specified</option><option>Bank transfer</option><option>Credit card reversal</option><option>Cheque</option><option>Cash</option><option>Account credit</option><option>Other</option></select></div></div><div class="col-12"><div class="form-group"><label class="required">Reason / credited item</label><textarea class="form-control" name="reason" rows="3" required placeholder="Describe the overcharge, returned service, or agreed credit"></textarea></div></div><div class="col-12"><div class="form-group mb-0"><label>Reference</label><input class="form-control" name="reference" placeholder="Transaction, approval, or bank reference"></div></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Close</button><button class="btn btn-warning" type="submit" data-confirm="Create this partial-refund credit note? The accounting record cannot be deleted."><i class="fal fa-file-minus mr-1"></i>Create credit note</button></div></form></div></div></div>

<?php if(empty($invoice['adjustments'])): ?><div class="modal fade" id="modal-cancel-invoice" tabindex="-1" role="dialog" aria-labelledby="cancel-invoice-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="post" action="<?= e(url('invoice',['id'=>(int)$invoice['id']])) ?>"><div class="modal-header"><div><span class="eyebrow text-danger">FULL REVERSAL</span><h2 class="modal-title fs-xl" id="cancel-invoice-title">Cancel this invoice</h2><p class="mb-0 text-muted">Creates a permanent cancellation certificate for the full invoice value.</p></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="create_invoice_adjustment"><input type="hidden" name="invoice_id" value="<?= (int)$invoice['id'] ?>"><input type="hidden" name="adjustment_type" value="cancellation"><div class="invoice-cancel-warning"><i class="fal fa-exclamation-triangle"></i><div><strong>Full reversal: <?= e(money($invoice['total'])) ?></strong><p>This marks the invoice cancelled and sets its net value and balance to zero. Existing payment history remains visible.</p></div></div><div class="form-group"><label class="required">Cancellation date</label><input class="form-control" type="date" name="adjustment_date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="form-group"><label class="required">Reason for cancellation</label><textarea class="form-control" name="reason" rows="4" required placeholder="Explain why the invoice is being cancelled"></textarea></div><div class="form-group"><label>Refund / reversal method</label><select class="custom-select" name="method"><option value="">Not applicable</option><option>Bank transfer</option><option>Credit card reversal</option><option>Cheque</option><option>Cash</option><option>Account credit</option><option>Other</option></select></div><div class="form-group mb-0"><label>Reference</label><input class="form-control" name="reference" placeholder="Approval or transaction reference"></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Keep invoice</button><button class="btn btn-danger" type="submit" data-confirm="Cancel this invoice and issue a permanent cancellation certificate?"><i class="fal fa-ban mr-1"></i>Cancel & issue certificate</button></div></form></div></div></div><?php endif; ?>
<?php endif; ?>
