<?php
$statuses=['draft'=>'Draft','sent'=>'Sent','partially_paid'=>'Partially paid','paid'=>'Paid','overdue'=>'Overdue','partially_refunded'=>'Partially refunded','refunded'=>'Refunded','cancelled'=>'Cancelled'];
$invoiceProjects=$options['invoice_projects']??$options['projects'];
?>
<div class="page-title-wrap invoice-page-title"><div><span class="eyebrow">FINANCIAL OPERATIONS</span><h1>Invoices & Payments</h1><p>Create detailed milestone invoices, select deposit instructions, track collections, and produce branded PDFs.</p><?php if(!empty($invoiceProfile['ocn_bin'])): ?><p class="mb-0"><strong>Number (OCN/BIN):</strong> <?= e($invoiceProfile['ocn_bin']) ?></p><?php endif; ?></div><button class="btn btn-primary" data-toggle="modal" data-target="#modal-invoice"><i class="fal fa-file-invoice-dollar mr-1"></i> New invoice</button></div>

<div class="invoice-kpis">
    <div><span>Gross issued</span><strong><?= e(money($summary['gross_issued'])) ?></strong><small><?= (int)$summary['issued_count'] ?> issued invoices</small></div>
    <div class="invoice-kpi-negative"><span>Cancelled</span><strong>−<?= e(money($summary['cancelled_total'])) ?></strong><small><?= (int)$summary['cancellation_count'] ?> certificates</small></div>
    <div class="invoice-kpi-negative"><span>Partial refunds</span><strong>−<?= e(money($summary['refunded_total'])) ?></strong><small><?= (int)$summary['refund_count'] ?> credit notes</small></div>
    <div class="invoice-kpi-net"><span>Net invoiced</span><strong><?= e(money($summary['net_invoiced'])) ?></strong><small>After all reversals</small></div>
    <div><span>Collected</span><strong><?= e(money($summary['collected'])) ?></strong><small>Recorded payments</small></div>
    <div><span>Outstanding</span><strong><?= e(money($summary['outstanding'])) ?></strong><small>Adjusted receivables</small></div>
</div>

<section class="panel invoice-filter-panel"><div class="panel-container show"><div class="panel-content py-3"><form method="get" action="<?= e(url('invoices')) ?>" class="invoice-filter-grid">
    <div><label for="invoice_filter_client">Client</label><select class="custom-select custom-select-sm" id="invoice_filter_client" name="client_id"><option value="">All clients</option><?php foreach($options['clients'] as $client): ?><option value="<?= (int)$client['id'] ?>" <?= (int)($filters['client_id']??0)===(int)$client['id']?'selected':'' ?>><?= e($client['name']) ?></option><?php endforeach; ?></select></div>
    <div><label for="invoice_filter_project">Project</label><select class="custom-select custom-select-sm" id="invoice_filter_project" name="project_id"><option value="">All projects</option><?php foreach($invoiceProjects as $project): ?><option value="<?= (int)$project['id'] ?>" <?= (int)($filters['project_id']??0)===(int)$project['id']?'selected':'' ?>><?= e($project['name']) ?></option><?php endforeach; ?></select></div>
    <div><label for="invoice_filter_status">Status</label><select class="custom-select custom-select-sm" id="invoice_filter_status" name="status"><option value="">All statuses</option><?php foreach($statuses as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($filters['status']??'')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>
    <div><label for="invoice_filter_from">Issued from</label><input class="form-control form-control-sm" id="invoice_filter_from" type="date" name="from" value="<?= e($filters['from']??'') ?>"></div>
    <div><label for="invoice_filter_to">Issued to</label><input class="form-control form-control-sm" id="invoice_filter_to" type="date" name="to" value="<?= e($filters['to']??'') ?>"></div>
    <div class="invoice-filter-actions"><button class="btn btn-sm btn-primary"><i class="fal fa-filter mr-1"></i> Apply</button><a class="btn btn-sm btn-outline-secondary" href="<?= e(url('invoices')) ?>">Clear</a></div>
</form></div></div></section>

<section class="panel"><div class="panel-container show"><div class="panel-content"><div class="data-toolbar"><div class="input-group table-search"><div class="input-group-prepend"><span class="input-group-text bg-white border-right-0"><i class="fal fa-search text-muted"></i></span></div><input type="search" class="form-control border-left-0" placeholder="Search invoice, client, project, or milestone…" data-table-search></div><span class="text-muted fs-sm"><strong><?= count($rows) ?></strong> invoices</span></div><div class="table-responsive"><table class="table table-hover invoice-table" data-agency-table><thead><tr><th>Invoice</th><th>Client / Project</th><th>Milestone</th><th>Issued</th><th>Original</th><th>Adjustments</th><th>Net value</th><th>Paid</th><th>Balance</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>
<?php foreach($rows as $row): $displayStatus=((float)$row['amount_due']>0&&!in_array($row['status'],['draft','cancelled','refunded'],true)&&$row['due_date']<date('Y-m-d'))?'overdue':$row['status']; ?>
<tr data-table-row><td><a class="font-weight-bold" href="<?= e(agency_url('invoice',['id'=>(int)$row['id']])) ?>"><?= e($row['invoice_number']) ?></a><small><?= (int)$row['item_count'] ?> line item<?= (int)$row['item_count']===1?'':'s' ?></small></td><td><strong><?= e($row['business_name']) ?></strong><small><?= e($row['project_name']?:'No project linked') ?></small></td><td><?= e($row['milestone_title']?:'General billing') ?><small><?= e($row['purchase_order_number']?'PO '.$row['purchase_order_number']:'') ?></small></td><td><?= e(date('M j, Y',strtotime($row['issue_date']))) ?><small>Due <?= e(date('M j',strtotime($row['due_date']))) ?></small></td><td><strong><?= e(money($row['total'])) ?></strong><small><?= e($row['currency']??'CAD') ?></small></td><td><?= (float)$row['adjustment_total']>0?'<strong class="text-danger">−'.e(money($row['adjustment_total'])).'</strong><small>'.(int)$row['adjustment_count'].' document'.((int)$row['adjustment_count']===1?'':'s').'</small>':'—' ?></td><td><strong><?= e(money($row['adjusted_total'])) ?></strong></td><td><?= e(money($row['amount_paid'])) ?></td><td><strong><?= e(money($row['amount_due'])) ?></strong></td><td><span class="badge badge-soft-<?= in_array($displayStatus,['paid','refunded'],true)?'success':(in_array($displayStatus,['overdue','cancelled'],true)?'danger':($displayStatus==='draft'?'secondary':'warning')) ?>"><?= e($statuses[$displayStatus]??ucwords(str_replace('_',' ',$displayStatus))) ?></span></td><td class="text-right text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="<?= e(agency_url('invoice',['id'=>(int)$row['id']])) ?>"><i class="fal fa-eye"></i></a><a class="btn btn-sm btn-outline-primary" href="<?= e(agency_url('invoice_pdf',['id'=>(int)$row['id']])) ?>"><i class="fal fa-file-pdf"></i></a><?php if(!in_array($row['status'],['paid','cancelled','refunded'],true)&&(float)$row['amount_due']>0): ?><button class="btn btn-sm btn-outline-success" data-toggle="modal" data-target="#modal-payment" data-payment data-id="<?= (int)$row['id'] ?>" data-number="<?= e($row['invoice_number']) ?>" data-due="<?= e((string)$row['amount_due']) ?>"><i class="fal fa-dollar-sign"></i></button><?php endif; ?></td></tr>
<?php endforeach; ?>
<?php if(!$rows): ?><tr><td colspan="11"><div class="empty-state"><i class="fal fa-file-invoice-dollar"></i><h3>No invoices match</h3><p class="text-muted">Clear the filters or create the first detailed invoice.</p></div></td></tr><?php endif; ?>
</tbody></table></div></div></div></section>

<section class="panel invoice-adjustment-report"><div class="panel-hdr"><div><h2>Invoice adjustment report</h2><small>Cancellation certificates and partial-refund credit notes</small></div><div class="panel-toolbar"><span class="badge badge-soft-primary"><?= (int)$summary['cancellation_count']+(int)$summary['refund_count'] ?> documents</span></div></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Document</th><th>Original invoice</th><th>Client</th><th>Date</th><th>Reason</th><th>Value</th><th class="text-right">PDF</th></tr></thead><tbody><?php foreach($summary['recent_adjustments'] as $adjustment): ?><tr><td><strong><?= e($adjustment['adjustment_number']) ?></strong><small class="d-block text-muted"><?= $adjustment['type']==='cancellation'?'Cancellation certificate':'Partial refund / credit note' ?></small></td><td><a href="<?= e(agency_url('invoice',['id'=>(int)$adjustment['invoice_id']])) ?>"><?= e($adjustment['invoice_number']) ?></a></td><td><?= e($adjustment['business_name']) ?></td><td><?= e(date('M j, Y',strtotime($adjustment['adjustment_date']))) ?></td><td><?= e($adjustment['reason']) ?></td><td class="text-danger font-weight-bold">−<?= e(money($adjustment['total'])) ?></td><td class="text-right"><a class="btn btn-sm btn-outline-primary" href="<?= e(agency_url('invoice_adjustment_pdf',['id'=>(int)$adjustment['id']])) ?>"><i class="fal fa-file-pdf mr-1"></i>Download</a></td></tr><?php endforeach; ?><?php if(!$summary['recent_adjustments']): ?><tr><td colspan="7"><div class="empty-state py-4"><i class="fal fa-receipt"></i><h3>No adjustments recorded</h3><p class="text-muted">Cancellation certificates and credit notes will appear here.</p></div></td></tr><?php endif; ?></tbody></table></div></div></section>

<div class="modal fade" id="modal-invoice" tabindex="-1" role="dialog" aria-labelledby="modal-invoice-title" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><form method="post" action="<?= e(url('invoices')) ?>" id="invoice-create-form"><div class="modal-header"><div><span class="eyebrow">BILLING WORKSPACE</span><h2 class="modal-title" id="modal-invoice-title">Create detailed invoice</h2><p class="mb-0 text-muted">Connect billing to a client, project, milestone, and deposit account.</p></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="create_invoice">
<div class="invoice-form-section"><h3>Billing context</h3><div class="row"><div class="col-md-6"><div class="form-group"><label class="required" for="invoice_client">Client</label><select class="custom-select" id="invoice_client" name="client_id" required data-client-filter="invoice_project"><option value="">Select client</option><?php foreach($options['clients'] as $client): ?><option value="<?= (int)$client['id'] ?>"><?= e($client['name']) ?></option><?php endforeach; ?></select></div></div><div class="col-md-6"><div class="form-group"><label for="invoice_project">Project</label><select class="custom-select" id="invoice_project" name="project_id"><option value="">No project</option><?php foreach($invoiceProjects as $project): ?><option value="<?= (int)$project['id'] ?>" data-client="<?= (int)$project['client_id'] ?>"><?= e($project['name'].(($project['status']??'')==='completed'?' · completed':'')) ?></option><?php endforeach; ?></select></div></div><div class="col-md-6"><div class="form-group"><label for="invoice_bank">Deposit bank account</label><select class="custom-select" id="invoice_bank" name="bank_account_id"><option value="">No bank details on invoice</option><?php foreach($bankAccounts as $bank): ?><option value="<?= (int)$bank['id'] ?>" <?= $bank['is_default']?'selected':'' ?>><?= e($bank['account_name'].' · '.$bank['bank_name'].' · '.$bank['currency']) ?></option><?php endforeach; ?></select><small class="form-text text-muted">Manage bank details in Settings.</small></div></div><div class="col-md-3"><div class="form-group"><label class="required" for="invoice_due">Due date</label><input class="form-control" id="invoice_due" type="date" name="due_date" value="<?= e(date('Y-m-d',strtotime('+14 days'))) ?>" required></div></div><div class="col-md-3"><div class="form-group"><label for="invoice_status">Issue as</label><select class="custom-select" id="invoice_status" name="status"><option value="sent">Sent / issued</option><option value="draft">Draft</option></select></div></div><div class="col-md-3"><div class="form-group"><label for="invoice_currency">Currency</label><input class="form-control" id="invoice_currency" name="currency" value="CAD" maxlength="10"></div></div><div class="col-md-3"><div class="form-group"><label for="invoice_po">PO / reference</label><input class="form-control" id="invoice_po" name="purchase_order_number"></div></div></div></div>
<div class="invoice-form-section"><h3>Milestone & payment request</h3><div class="row"><div class="col-md-5"><div class="form-group"><label for="invoice_milestone">Milestone</label><input class="form-control" id="invoice_milestone" name="milestone_title" placeholder="e.g. Website design approved"></div></div><div class="col-md-7"><div class="form-group"><label for="invoice_milestone_details">Milestone details</label><input class="form-control" id="invoice_milestone_details" name="milestone_description" placeholder="What was achieved and why payment is now due"></div></div></div></div>
<div class="invoice-form-section"><div class="d-flex justify-content-between align-items-center mb-3"><h3 class="mb-0">Line items</h3><button class="btn btn-sm btn-outline-primary" type="button" data-add-invoice-line><i class="fal fa-plus mr-1"></i>Add line</button></div><div data-invoice-lines><div class="invoice-line"><div><label>Description</label><input class="form-control" name="item_description[]" required placeholder="Service, phase, or deliverable"></div><div><label>Qty</label><input class="form-control" type="number" min="0.01" step="0.01" name="item_quantity[]" value="1" required data-invoice-quantity></div><div><label>Unit price</label><input class="form-control" type="number" min="0.01" step="0.01" name="item_unit_price[]" required data-invoice-price></div><div><label>Line total</label><strong data-invoice-line-total>$0.00</strong></div><button class="btn btn-sm btn-outline-danger" type="button" data-remove-invoice-line title="Remove line"><i class="fal fa-trash-alt"></i></button></div></div><div class="invoice-calculation"><label>Discount <input class="form-control" type="number" min="0" step="0.01" name="discount" value="0" data-invoice-discount></label><label>Tax % <input class="form-control" type="number" min="0" step="0.01" name="tax_percent" value="13" data-invoice-tax></label><div><span>Estimated total</span><strong data-invoice-total>$0.00</strong></div></div></div>
<div class="invoice-form-section"><h3>Terms & notes</h3><div class="row"><div class="col-md-7"><div class="form-group"><label for="invoice_terms">Payment terms</label><textarea class="form-control" id="invoice_terms" name="payment_terms" rows="3" placeholder="Default terms from Settings will be used if blank."></textarea></div></div><div class="col-md-5"><div class="form-group"><label for="invoice_notes">Internal / invoice notes</label><textarea class="form-control" id="invoice_notes" name="notes" rows="3"></textarea></div></div></div></div>
</div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit"><i class="fal fa-save mr-1"></i>Create invoice</button></div></form></div></div></div>

<template id="invoice-line-template"><div class="invoice-line"><div><label>Description</label><input class="form-control" name="item_description[]" required placeholder="Service, phase, or deliverable"></div><div><label>Qty</label><input class="form-control" type="number" min="0.01" step="0.01" name="item_quantity[]" value="1" required data-invoice-quantity></div><div><label>Unit price</label><input class="form-control" type="number" min="0.01" step="0.01" name="item_unit_price[]" required data-invoice-price></div><div><label>Line total</label><strong data-invoice-line-total>$0.00</strong></div><button class="btn btn-sm btn-outline-danger" type="button" data-remove-invoice-line><i class="fal fa-trash-alt"></i></button></div></template>

<div class="modal fade" id="modal-payment" tabindex="-1" role="dialog" aria-labelledby="payment-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="post" action="<?= e(url('invoices')) ?>"><div class="modal-header"><div><span class="eyebrow">COLLECTIONS</span><h2 id="payment-title" class="modal-title">Record payment · <span id="payment_invoice"></span></h2></div><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?= e(\AgencyOS\Csrf::token()) ?>"><input type="hidden" name="action" value="record_payment"><input type="hidden" id="payment_invoice_id" name="invoice_id"><div class="form-group"><label class="required" for="payment_amount">Amount</label><input class="form-control" id="payment_amount" type="number" step="0.01" min="0.01" name="amount" required></div><div class="form-group"><label class="required">Payment date</label><input class="form-control" type="date" name="payment_date" value="<?= e(date('Y-m-d')) ?>" required></div><div class="form-group"><label class="required">Method</label><select class="custom-select" name="method" required><option>Bank transfer</option><option>Credit card</option><option>Cheque</option><option>Cash</option><option>Other</option></select></div><div class="form-group"><label>Reference</label><input class="form-control" name="reference"></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Cancel</button><button class="btn btn-success" type="submit">Record payment</button></div></form></div></div></div>

<script>
document.addEventListener('DOMContentLoaded',function(){var form=document.getElementById('invoice-create-form');if(!form)return;var lines=form.querySelector('[data-invoice-lines]'),template=document.getElementById('invoice-line-template');function money(value){return '$'+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});}function calculate(){var subtotal=0;lines.querySelectorAll('.invoice-line').forEach(function(line){var qty=parseFloat(line.querySelector('[data-invoice-quantity]').value)||0,price=parseFloat(line.querySelector('[data-invoice-price]').value)||0,total=qty*price;subtotal+=total;line.querySelector('[data-invoice-line-total]').textContent=money(total);});var discount=parseFloat(form.querySelector('[data-invoice-discount]').value)||0,tax=parseFloat(form.querySelector('[data-invoice-tax]').value)||0,total=Math.max(0,subtotal-discount);total+=total*tax/100;form.querySelector('[data-invoice-total]').textContent=money(total);}form.addEventListener('input',calculate);form.addEventListener('click',function(event){var add=event.target.closest('[data-add-invoice-line]'),remove=event.target.closest('[data-remove-invoice-line]');if(add){lines.appendChild(template.content.cloneNode(true));calculate();}if(remove&&lines.querySelectorAll('.invoice-line').length>1){remove.closest('.invoice-line').remove();calculate();}});calculate();});
</script>
