<?php
$locale=(string)request()->query('lang',$quote['locale']??'en');if(!in_array($locale,['en','ar','he'],true)){$locale='en';}
$rtl=$locale!=='en';
$publicMode=$publicMode??false;
$loc=static function(array $row,string $field)use($locale):string{$key=$locale==='en'?$field:$field.'_'.$locale;return (string)($row[$key]??$row[$field]??'');};
$shareUrl=url('quote/share/'.$quote['share_token']).'?lang='.$locale;
?>
<?php if(!$publicMode): ?><div class="quote-page-heading no-print"><div><span class="eyebrow">PROPOSAL <?= e($quote['proposal_number']) ?></span><h1><?= e($quote['business_name']) ?></h1><p>Revision <?= (int)$quote['revision'] ?> · Sent <?= (int)$quote['sent_count'] ?> times · <?= e(ucfirst($quote['status'])) ?></p></div><div class="quote-heading-actions"><a class="btn btn-outline-secondary" href="<?= e(agency_url('saved_quotes')) ?>"><i class="fal fa-arrow-left"></i> Saved quotes</a><a class="btn btn-outline-secondary" href="<?= e(agency_url('quote_studio',['id'=>$quote['id']])) ?>"><i class="fal fa-pencil"></i> Edit</a><button class="btn btn-primary" onclick="window.print()"><i class="fal fa-file-pdf"></i> Print / PDF</button></div></div><?php endif; ?>
<div class="quote-language-row no-print"><strong><?= $publicMode?'Language':'Client language' ?></strong><?php foreach($locales as $code=>$language): ?><?php $languageUrl=$publicMode?route('quote.public',['token'=>$quote['share_token'],'lang'=>$code]):agency_url('quote_view',['id'=>$quote['id'],'lang'=>$code]); ?><a class="<?= $locale===$code?'active':'' ?>" href="<?= e($languageUrl) ?>"><?= e($language['label']) ?></a><?php endforeach; ?><?php if(!$publicMode): ?><label><span>Share link</span><input readonly value="<?= e($shareUrl) ?>" onclick="this.select()"></label><?php endif; ?><button class="btn btn-outline-secondary ml-auto" onclick="window.print()"><i class="fal fa-print"></i> Print / PDF</button></div>
<article class="client-proposal" dir="<?= $rtl?'rtl':'ltr' ?>">
    <header><div class="client-proposal-brand"><img src="<?= e(asset('img/360-logo-final-exact.png')) ?>" alt="360 Creative Agency"><strong>360 Creative Agency</strong></div><div><span><?= $locale==='ar'?'ملخص العرض':($locale==='he'?'סיכום הצעה':'PROPOSAL SUMMARY') ?></span><strong><?= e($quote['proposal_number']) ?></strong></div></header>
    <section class="client-proposal-meta"><div><small><?= $locale==='ar'?'بيانات العميل والشركة':($locale==='he'?'פרטי הלקוח והעסק':'CLIENT AND BUSINESS DETAILS') ?></small><h2><?= e($quote['business_name']) ?></h2><p><?= e($quote['contact_name']) ?> · <?= e($quote['contact_email']) ?></p><?php if($quote['website']): ?><p><?= e($quote['website']) ?></p><?php endif; ?></div><dl><div><dt><?= $locale==='ar'?'التاريخ':($locale==='he'?'תאריך':'Date') ?></dt><dd><?= e(date('Y-m-d',strtotime($quote['created_at']))) ?></dd></div><div><dt><?= $locale==='ar'?'صالح حتى':($locale==='he'?'בתוקף עד':'Valid until') ?></dt><dd><?= e($quote['valid_until']) ?></dd></div><div><dt><?= $locale==='ar'?'الباقة':($locale==='he'?'חבילה':'Package') ?></dt><dd><?= e(strtoupper($quote['selected_tier'])) ?></dd></div><div><dt>CAD</dt><dd>Canadian Dollar</dd></div></dl></section>
    <section class="client-proposal-scope"><h3><?= $locale==='ar'?'الخدمات المختارة':($locale==='he'?'שירותים נבחרים':'SELECTED SERVICES') ?></h3><?php foreach($quote['items'] as $index=>$item): ?><div class="client-proposal-item"><span><?= $index+1 ?></span><div><strong><?= e($loc($item,'title')) ?></strong><small><?= e($loc($item,'description')) ?></small><em><?= e($item['category']??'') ?></em></div><b><?= money($item['total']) ?><?= ($item['item_type']??'service')==='membership'?'/mo':'' ?></b></div><?php endforeach; ?><div class="client-proposal-subtotal"><strong><?= $locale==='ar'?'المجموع قبل الضريبة':($locale==='he'?'סכום לפני מס':'Subtotal before tax') ?></strong><b><?= money($quote['subtotal']) ?></b></div></section>
    <section class="client-proposal-total"><div><span><?= $locale==='ar'?'المجموع قبل الضريبة':($locale==='he'?'סכום לפני מס':'Total before tax') ?></span><b><?= money($quote['subtotal']) ?></b></div><div><span>HST <?= e(rtrim(rtrim(number_format((float)$quote['tax_percent'],2),'0'),'.')) ?>%</span><b><?= money($quote['tax']) ?></b></div><div class="grand"><span><?= $locale==='ar'?'المجموع الكلي':($locale==='he'?'סה״כ':'Grand total') ?></span><b><?= money($quote['total']) ?></b></div></section>
    <footer><div><strong>360 Creative Agency</strong><span><?= e($company['phone']) ?></span><span><?= e($company['email']) ?></span><span><?= e($company['website']) ?></span></div><div><span><?= e($company['address']) ?></span><span>Prices in CAD. Third-party costs are separate unless expressly included.</span></div></footer>
</article>
<?php if(!$publicMode): ?><section class="quote-delivery-card no-print"><div><h3>Send or resend this quote</h3><p>Every send is recorded. The client can open the same secure link in English, Arabic, or Hebrew.</p></div><form method="post" action="<?= e(agency_url('quote_view',['id'=>$quote['id']])) ?>" id="quote-delivery-form">@csrf<input type="hidden" name="action" value="record_quote_delivery"><input type="hidden" name="proposal_id" value="<?= (int)$quote['id'] ?>"><input type="hidden" name="locale" value="<?= e($locale) ?>"><input type="email" required name="recipient_email" value="<?= e($quote['contact_email']) ?>"><button class="btn btn-primary"><i class="fal fa-paper-plane"></i> Prepare email &amp; record send</button></form><?php if($quote['deliveries']): ?><div class="delivery-history"><?php foreach($quote['deliveries'] as $delivery): ?><span><i class="fal fa-check-circle"></i><?= e($delivery['recipient_email']) ?> · <?= e(strtoupper($delivery['locale'])) ?> · <?= e(date('M j, Y g:i A',strtotime($delivery['sent_at']))) ?></span><?php endforeach; ?></div><?php endif; ?></section>
<script>document.getElementById('quote-delivery-form').addEventListener('submit',function(){var email=this.elements.recipient_email.value;var subject=<?= json_encode('Proposal '.$quote['proposal_number'].' from 360 Creative Agency') ?>;var body=<?= json_encode("Hello ".$quote['contact_name'].",\n\nPlease review your proposal here:\n".$shareUrl."\n\nThank you,\n360 Creative Agency") ?>;window.open('mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body));});</script><?php endif; ?>
