<?php
$s = $quoteSettings;
$allPackages = array_merge($s['packages'], $s['supportPackages']);
$packageOptions = array_map(static fn(array $package): array => ['id'=>(int)$package['id'],'name'=>$package['name'],'tier'=>$package['tier'],'package_type'=>$package['package_type']], $allPackages);
?>

<div class="quote-page-heading">
    <div><span class="eyebrow">QUOTE CATALOG</span><h1>Quote Settings</h1><p>Build one-time setup and ongoing support-contract packages from one shared service catalog.</p></div>
    <button class="btn btn-primary" data-toggle="modal" data-target="#quote-service-modal" data-service-id=""><i class="fal fa-plus mr-1"></i> Add service</button>
</div>

<section class="quote-settings-section" id="setup-packages">
    <header><div><span class="quote-heading-icon"><i class="fal fa-box-open"></i></span><div><h2>One-time setup packages</h2><p>Create packages and control one-time service pricing, client scope, and delivery-item values.</p></div></div><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#quote-package-modal" data-package="" data-package-type="quote_setup"><i class="fal fa-plus mr-1"></i> Add setup package</button></header>
    <div class="quote-package-settings-grid">
        <?php foreach($s['packages'] as $package): ?>
            <article class="quote-package-settings-card">
                <div class="quote-package-settings-head"><div><span><?= e(strtoupper($package['tier'])) ?></span><h3><?= e($package['name']) ?></h3><p><?= e($package['description']) ?></p></div><button class="quote-icon-button" data-toggle="modal" data-target="#quote-package-modal" data-package-type="quote_setup" data-package='<?= e(json_encode($package,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>' title="Edit package"><i class="fal fa-pencil"></i></button></div>
                <div class="quote-package-item-list">
                    <?php if(!$package['items']): ?><p class="quote-package-empty">No services yet. Add the first service below.</p><?php endif; ?>
                    <?php foreach($package['items'] as $item): ?>
                        <?php $deliveryItems = array_values(array_filter($item['work_items']??[], static fn(array $work): bool => (bool)$work['included'])); $editableItem=$item; ?>
                        <div><div><strong><?= e($item['name']) ?></strong><small><?= e($item['description']?:$item['service_description']) ?></small><span class="quote-work-count"><i class="fal fa-tasks"></i> <?= count($deliveryItems) ?> package items</span></div><b><?= money($item['unit_price']) ?></b><button class="quote-icon-button" data-toggle="modal" data-target="#quote-package-item-modal" data-item='<?= e(json_encode($editableItem,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>' title="Edit package service and items"><i class="fal fa-pencil"></i></button><form method="post" action="<?= e(url('quote_settings')) ?>" onsubmit="return confirm('Remove this service from the package?')">@csrf<input type="hidden" name="action" value="remove_quote_package_item"><input type="hidden" name="package_item_id" value="<?= (int)$item['id'] ?>"><button class="quote-icon-button quote-remove-button" title="Remove item"><i class="fal fa-trash-alt"></i></button></form></div>
                    <?php endforeach; ?>
                </div>
                <footer class="quote-package-card-actions"><button class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#quote-package-add-item-modal" data-package-id="<?= (int)$package['id'] ?>" data-package-name="<?= e($package['name']) ?>"><i class="fal fa-plus mr-1"></i> Add service to package</button></footer>
            </article>
        <?php endforeach; ?>
    </div>
</section>

<section class="quote-settings-section" id="support-contract-packages">
    <header><div><span class="quote-heading-icon"><i class="fal fa-file-signature"></i></span><div><h2>Support contract packages</h2><p>Build monthly packages with their own services, prices, scopes, and delivery items. The contract term is selected at quote time.</p></div></div><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#quote-package-modal" data-package="" data-package-type="support_contract"><i class="fal fa-plus mr-1"></i> Add support package</button></header>
    <div class="quote-package-settings-grid">
        <?php foreach($s['supportPackages'] as $package): ?>
            <article class="quote-package-settings-card quote-support-package-card">
                <div class="quote-package-settings-head"><div><span>MONTHLY · <?= e(strtoupper($package['tier'])) ?></span><h3><?= e($package['name']) ?></h3><p><?= e($package['description']) ?></p></div><button class="quote-icon-button" data-toggle="modal" data-target="#quote-package-modal" data-package-type="support_contract" data-package='<?= e(json_encode($package,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>' title="Edit support package"><i class="fal fa-pencil"></i></button></div>
                <div class="quote-package-item-list">
                    <?php if(!$package['items']): ?><p class="quote-package-empty">No monthly services yet. Add the first service below.</p><?php endif; ?>
                    <?php foreach($package['items'] as $item): ?>
                        <?php $deliveryItems=array_values(array_filter($item['work_items']??[],static fn(array $work):bool=>(bool)$work['included'])); ?>
                        <div><div><strong><?= e($item['name']) ?></strong><small><?= e($item['description']?:$item['service_description']) ?></small><span class="quote-work-count"><i class="fal fa-tasks"></i> <?= count($deliveryItems) ?> package items</span></div><b><?= money($item['unit_price']) ?>/mo</b><button class="quote-icon-button" data-toggle="modal" data-target="#quote-package-item-modal" data-item='<?= e(json_encode($item,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>' title="Edit package service and items"><i class="fal fa-pencil"></i></button><form method="post" action="<?= e(url('quote_settings')) ?>" onsubmit="return confirm('Remove this service from the support package?')">@csrf<input type="hidden" name="action" value="remove_quote_package_item"><input type="hidden" name="package_item_id" value="<?= (int)$item['id'] ?>"><button class="quote-icon-button quote-remove-button" title="Remove item"><i class="fal fa-trash-alt"></i></button></form></div>
                    <?php endforeach; ?>
                </div>
                <footer class="quote-package-card-actions"><button class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#quote-package-add-item-modal" data-package-id="<?= (int)$package['id'] ?>" data-package-name="<?= e($package['name']) ?>"><i class="fal fa-plus mr-1"></i> Add monthly service</button></footer>
            </article>
        <?php endforeach; ?>
    </div>
</section>

<section class="quote-settings-section" id="service-catalog">
    <header><div><span class="quote-heading-icon"><i class="fal fa-concierge-bell"></i></span><div><h2>Service catalog &amp; item templates</h2><p>Define the reusable items that packages can copy and customise.</p></div></div><span class="quote-count"><?= count($s['services']) ?> services</span></header>
    <div class="table-responsive"><table class="quote-list-table"><thead><tr><th>Service</th><th>Delivery items</th><th>Category</th><th>Pricing</th><th>Client price</th><th>Quote</th><th></th></tr></thead><tbody>
    <?php foreach($s['services'] as $service): ?>
        <tr><td><strong><?= e($service['name']) ?></strong><small><?= e($service['description']) ?></small></td><td><strong><?= count($service['work_items']) ?></strong><small>reusable items</small></td><td><?= e($service['category_name']) ?></td><td><?= e(ucwords(str_replace('_',' ',$service['pricing_type']))) ?></td><td><strong><?= money($service['default_price']) ?></strong></td><td><span class="badge badge-<?= $service['quote_enabled']?'success':'secondary' ?>"><?= $service['quote_enabled']?'Visible':'Hidden' ?></span></td><td class="text-right"><button class="quote-icon-button quote-manage-service" data-toggle="modal" data-target="#quote-service-modal" data-service-id="<?= (int)$service['id'] ?>" title="Edit service and item templates"><i class="fal fa-tasks"></i></button></td></tr>
    <?php endforeach; ?>
    </tbody></table></div>
</section>

<section class="quote-settings-section">
    <header><div><span class="quote-heading-icon"><i class="fal fa-shield-check"></i></span><div><h2>Technical support plans</h2><p>These percentage-based plans remain calculated from the selected one-time setup subtotal.</p></div></div></header>
    <div class="quote-plan-settings-grid"><?php foreach($s['supportPlans'] as $plan): ?><article><span>TECHNICAL SUPPORT</span><h3><?= e($plan['name']) ?></h3><p><?= e($plan['description']) ?></p><strong><?= (float)$plan['rate_percent'] ?>% × <?= (float)$plan['multiplier'] ?></strong><button class="quote-icon-button" data-toggle="modal" data-target="#quote-plan-modal" data-type="support" data-plan='<?= e(json_encode($plan,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>'><i class="fal fa-pencil"></i></button></article><?php endforeach; ?></div>
</section>

<div class="modal fade" id="quote-service-modal" tabindex="-1"><div class="modal-dialog modal-xl quote-service-builder-modal"><form class="modal-content" method="post" action="<?= e(url('quote_settings')) ?>">@csrf
    <input type="hidden" name="action" value="save_quote_service"><input type="hidden" name="service_id"><input type="hidden" name="work_items_present" value="1">
    <div class="modal-header"><div><span class="eyebrow">SERVICE CATALOG</span><h3 class="modal-title">Add service</h3><p class="mb-0 text-muted">Define the master service and reusable item templates.</p></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body">
        <div class="quote-form-grid service-base-fields">
            <label class="quote-field"><span class="required">Name (English)</span><input required name="name"></label><label class="quote-field"><span>Name (Arabic)</span><input dir="rtl" name="name_ar"></label><label class="quote-field"><span>Name (Hebrew)</span><input dir="rtl" name="name_he"></label>
            <label class="quote-field"><span class="required">Category</span><select required name="category_id"><?php foreach($s['categories'] as $category): ?><option value="<?= (int)$category['id'] ?>"><?= e($category['name']) ?></option><?php endforeach; ?></select></label>
            <label class="quote-field"><span>Pricing type</span><select name="pricing_type"><?php foreach(['one_time','monthly','hourly','per_visit','per_project','custom'] as $type): ?><option value="<?= e($type) ?>"><?= e(ucwords(str_replace('_',' ',$type))) ?></option><?php endforeach; ?></select></label>
            <label class="quote-field"><span>Default client price</span><input type="number" min="0" step="0.01" name="default_price"></label><label class="quote-field"><span>Internal cost</span><input type="number" min="0" step="0.01" name="cost_estimate"></label><label class="quote-field"><span>Estimated hours</span><input type="number" min="0" step="0.1" name="estimated_hours"></label><label class="quote-field"><span>Quote sort</span><input type="number" min="0" name="quote_sort"></label>
            <label class="quote-field quote-field-wide"><span class="required">Description (English)</span><textarea required rows="3" name="description"></textarea></label><label class="quote-field"><span>Description (Arabic)</span><textarea dir="rtl" rows="3" name="description_ar"></textarea></label><label class="quote-field"><span>Description (Hebrew)</span><textarea dir="rtl" rows="3" name="description_he"></textarea></label>
            <div class="quote-check-row"><label><input type="checkbox" name="taxable" value="1" checked> Taxable</label><label><input type="checkbox" name="active" value="1" checked> Active</label><label><input type="checkbox" name="quote_enabled" value="1" checked> Visible in Quote Studio</label></div>
        </div>
        <section class="service-workflow-builder"><header><div><span class="quote-heading-icon"><i class="fal fa-project-diagram"></i></span><div><h4>Service item templates</h4><p>Packages copy these items and can customise them without changing this service.</p></div></div><button type="button" class="btn btn-outline-secondary btn-sm" id="add-service-work-item"><i class="fal fa-plus mr-1"></i> Add service item</button></header><div id="service-work-items"></div><div class="service-workflow-empty" id="service-workflow-empty"><i class="fal fa-tasks"></i><strong>No service items yet</strong><span>Add items such as Shooting Hours, Revisions, Weekly Posts, or Reporting.</span></div></section>
    </div>
    <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary"><i class="fal fa-save mr-1"></i> Save service &amp; items</button></div>
</form></div></div>

<div class="modal fade" id="quote-package-modal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= e(url('quote_settings')) ?>">@csrf<input type="hidden" name="action" value="save_quote_package"><input type="hidden" name="package_id"><div class="modal-header"><h3 class="modal-title">Add setup package</h3><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="quote-form-grid"><label class="quote-field"><span>Name (English)</span><input required name="name"></label><label class="quote-field"><span>Package code</span><input required maxlength="20" pattern="[a-z0-9_]+" name="tier" placeholder="enterprise"><small>Lowercase letters, numbers, and underscores.</small></label><label class="quote-field"><span>Display order</span><input type="number" min="1" name="display_order" value="99"></label><label class="quote-field"><span>Name (Arabic)</span><input dir="rtl" name="name_ar"></label><label class="quote-field"><span>Name (Hebrew)</span><input dir="rtl" name="name_he"></label><label class="quote-field quote-field-wide"><span>Description (English)</span><textarea required name="description"></textarea></label><label class="quote-field"><span>Description (Arabic)</span><textarea dir="rtl" name="description_ar"></textarea></label><label class="quote-field"><span>Description (Hebrew)</span><textarea dir="rtl" name="description_he"></textarea></label><label class="quote-field"><input type="checkbox" name="active" value="1" checked> Active in Quote Studio</label></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Save package</button></div></form></div></div>

<div class="modal fade" id="quote-package-add-item-modal" tabindex="-1"><div class="modal-dialog modal-xl quote-service-builder-modal"><form class="modal-content" method="post" action="<?= e(url('quote_settings')) ?>">@csrf<input type="hidden" name="action" value="add_quote_package_item"><input type="hidden" name="package_id"><input type="hidden" name="work_items_present" value="1"><div class="modal-header"><div><span class="eyebrow">PACKAGE SERVICE</span><h3 class="modal-title">Add service to package</h3><p class="mb-0 text-muted">The service items are copied below. Edit this package's version before saving.</p></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="quote-form-grid"><label class="quote-field quote-field-wide"><span>Service</span><select required name="service_id"><?php foreach($s['services'] as $service): ?><?php if($service['active']&&$service['quote_enabled']): ?><option value="<?= (int)$service['id'] ?>" data-service='<?= e(json_encode($service,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>'><?= e($service['name'].' — '.$service['category_name']) ?></option><?php endif; ?><?php endforeach; ?></select></label><label class="quote-field"><span>Package item price</span><input required type="number" min="0" step="0.01" name="unit_price"></label><label class="quote-field"><span>Sort order</span><input type="number" min="0" name="sort_order" value="99"></label><label class="quote-field quote-field-wide"><span>What this package includes (English)</span><textarea required rows="3" name="description"></textarea></label><label class="quote-field"><span>Arabic description</span><textarea dir="rtl" rows="3" name="description_ar"></textarea></label><label class="quote-field"><span>Hebrew description</span><textarea dir="rtl" rows="3" name="description_he"></textarea></label><label class="quote-field"><input type="checkbox" name="included" value="1" checked> Included by default</label></div><section class="package-work-item-editor"><h4>Package service items</h4><p>Change names, instructions, values, inclusion, or work type for this package only.</p><div id="package-add-work-items"></div></section></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Add service with items</button></div></form></div></div>

<div class="modal fade" id="quote-package-item-modal" tabindex="-1"><div class="modal-dialog modal-xl quote-service-builder-modal"><form class="modal-content" method="post" action="<?= e(url('quote_settings')) ?>">@csrf<input type="hidden" name="action" value="save_quote_package_item"><input type="hidden" name="package_item_id"><input type="hidden" name="work_items_present" value="1"><div class="modal-header"><div><h3>Edit package service &amp; items</h3><p class="mb-0 text-muted">These changes belong to this package and do not change the master service.</p></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="quote-form-grid"><label class="quote-field"><span>Item price</span><input required type="number" min="0" step="0.01" name="unit_price"></label><label class="quote-field"><span>Sort order</span><input type="number" min="0" name="sort_order"></label><label class="quote-field quote-field-wide"><span>What this tier includes (English)</span><textarea required rows="3" name="description"></textarea></label><label class="quote-field"><span>Arabic description</span><textarea dir="rtl" rows="3" name="description_ar"></textarea></label><label class="quote-field"><span>Hebrew description</span><textarea dir="rtl" rows="3" name="description_he"></textarea></label><label class="quote-field"><input type="checkbox" name="included" value="1"> Included by default</label></div><section class="package-work-item-editor"><h4>Package service items</h4><p>Edit the copied service items that will be offered in this package.</p><div id="package-edit-work-items"></div></section></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Save package service &amp; items</button></div></form></div></div>

<div class="modal fade" id="quote-plan-modal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= e(url('quote_settings')) ?>">@csrf<input type="hidden" name="action" value="save_quote_plan"><input type="hidden" name="plan_type"><input type="hidden" name="plan_id"><div class="modal-header"><h3>Edit plan</h3><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="quote-form-grid"><label class="quote-field"><span>Name (English)</span><input required name="name"></label><label class="quote-field"><span>Name (Arabic)</span><input dir="rtl" name="name_ar"></label><label class="quote-field"><span>Name (Hebrew)</span><input dir="rtl" name="name_he"></label><label class="quote-field quote-field-wide"><span>Description (English)</span><textarea required name="description"></textarea></label><label class="quote-field"><span>Description (Arabic)</span><textarea dir="rtl" name="description_ar"></textarea></label><label class="quote-field"><span>Description (Hebrew)</span><textarea dir="rtl" name="description_he"></textarea></label><div class="support-plan-fields"><label class="quote-field"><span>Rate %</span><input type="number" min="0" step="0.01" name="rate_percent"></label><label class="quote-field"><span>Multiplier</span><input type="number" min="0" step="0.01" name="multiplier"></label><label class="quote-field"><span>Duration months</span><input type="number" min="0" name="duration_months"></label></div><div class="membership-plan-fields"><label class="quote-field"><span>Monthly price</span><input type="number" min="0" step="0.01" name="monthly_price"></label><label class="quote-field"><input type="checkbox" name="featured" value="1"> Most popular</label></div><label class="quote-field"><input type="checkbox" name="active" value="1"> Active</label></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Save plan</button></div></form></div></div>

<script type="application/json" id="quote-settings-data"><?= json_encode(['services'=>$s['services'],'packages'=>$packageOptions],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<script>
window.addEventListener('DOMContentLoaded',function(){
    var settingsData=JSON.parse(document.getElementById('quote-settings-data').textContent||'{}'),packages=settingsData.packages||[],workflowHost=document.getElementById('service-work-items'),workflowEmpty=document.getElementById('service-workflow-empty'),workItemIndex=0;
    function fill(form,data){Object.keys(data||{}).forEach(function(key){var field=form.elements[key];if(!field)return;if(field.type==='checkbox')field.checked=Number(data[key])===1;else field.value=data[key]==null?'':data[key];});}
    function html(value){var node=document.createElement('div');node.textContent=value==null?'':String(value);return node.innerHTML;}
    function selected(value,expected){return String(value||'')===String(expected)?' selected':'';}function checked(value,defaultValue){return (value==null?defaultValue:Number(value)===1)?' checked':'';}function value(value){return value==null?'':value;}
    function scheduleOptions(current,inherit){return (inherit?'<option value="">Inherit service item</option>':'')+'<option value="one_time"'+selected(current,'one_time')+'>One time</option><option value="recurring"'+selected(current,'recurring')+'>Recurring</option>';}
    function frequencyOptions(current,inherit){return (inherit?'<option value="">Inherit service item</option>':'')+'<option value="daily"'+selected(current,'daily')+'>Daily</option><option value="weekly"'+selected(current,'weekly')+'>Weekly</option><option value="monthly"'+selected(current,'monthly')+'>Monthly</option><option value="yearly"'+selected(current,'yearly')+'>Yearly</option>';}
    function addWorkItem(item){item=item||{};var index=workItemIndex++,article=document.createElement('article');article.className='service-work-item-editor';article.dataset.workItemIndex=index;article.innerHTML='<header><div><span class="service-work-item-number">'+(workflowHost.children.length+1)+'</span><div><strong>'+(item.name?html(item.name):'New service item')+'</strong><small>Reusable master item</small></div></div><button type="button" class="quote-icon-button remove-service-work-item" title="Remove service item"><i class="fal fa-trash-alt"></i></button></header><div class="service-work-item-fields"><input type="hidden" name="work_items['+index+'][id]" value="'+html(value(item.id))+'"><label><span>Name (English) *</span><input required name="work_items['+index+'][name]" value="'+html(value(item.name))+'"></label><label><span>Name (Arabic)</span><input dir="rtl" name="work_items['+index+'][name_ar]" value="'+html(value(item.name_ar))+'"></label><label><span>Name (Hebrew)</span><input dir="rtl" name="work_items['+index+'][name_he]" value="'+html(value(item.name_he))+'"></label><label class="wide"><span>Task instructions (English)</span><textarea name="work_items['+index+'][task_description]" rows="2">'+html(value(item.task_description))+'</textarea></label><label><span>Task instructions (Arabic)</span><textarea dir="rtl" name="work_items['+index+'][task_description_ar]" rows="2">'+html(value(item.task_description_ar))+'</textarea></label><label><span>Task instructions (Hebrew)</span><textarea dir="rtl" name="work_items['+index+'][task_description_he]" rows="2">'+html(value(item.task_description_he))+'</textarea></label><label><span>Default work type</span><select name="work_items['+index+'][schedule_type]">'+scheduleOptions(item.schedule_type||'one_time',false)+'</select></label><label><span>Repeat frequency</span><select name="work_items['+index+'][frequency]">'+frequencyOptions(item.frequency||'weekly',false)+'</select></label></div>';article.querySelector('.remove-service-work-item').addEventListener('click',function(){if(!item.id||window.confirm('Remove this service item when the service is saved?')){article.remove();renumberWorkItems();}});article.querySelector('input[name$="[name]"]').addEventListener('input',function(){article.querySelector('header strong').textContent=this.value||'New service item';});workflowHost.appendChild(article);renumberWorkItems();}
    function packageWorkItemCard(item,index){var workId=item.service_work_item_id||item.id||'',base='work_items['+index+']',name=item.title||item.name||'',description=item.description||item.task_description||'',scope=item.scope_value||item.value_label||'';return '<article class="package-work-item-card"><header><span>'+(index+1)+'</span><strong>'+html(name||'Service item')+'</strong><label><input type="hidden" name="'+base+'[included]" value="0"><input type="checkbox" name="'+base+'[included]" value="1"'+checked(item.included,false)+'> Add to this package</label></header><input type="hidden" name="'+base+'[service_work_item_id]" value="'+html(workId)+'"><div class="package-work-item-fields"><label><span>Name (English)</span><input required name="'+base+'[name]" value="'+html(name)+'"></label><label><span>Name (Arabic)</span><input dir="rtl" name="'+base+'[name_ar]" value="'+html(item.title_ar||item.name_ar||'')+'"></label><label><span>Name (Hebrew)</span><input dir="rtl" name="'+base+'[name_he]" value="'+html(item.title_he||item.name_he||'')+'"></label><label class="wide"><span>Instructions (English)</span><textarea name="'+base+'[task_description]" rows="2">'+html(description)+'</textarea></label><label><span>Instructions (Arabic)</span><textarea dir="rtl" name="'+base+'[task_description_ar]" rows="2">'+html(item.description_ar||item.task_description_ar||'')+'</textarea></label><label><span>Instructions (Hebrew)</span><textarea dir="rtl" name="'+base+'[task_description_he]" rows="2">'+html(item.description_he||item.task_description_he||'')+'</textarea></label><label><span>Package value / scope</span><input name="'+base+'[value_label]" value="'+html(scope)+'" placeholder="e.g. 40 edited photos"></label><label><span>Arabic value</span><input dir="rtl" name="'+base+'[value_label_ar]" value="'+html(item.scope_value_ar||item.value_label_ar||'')+'"></label><label><span>Hebrew value</span><input dir="rtl" name="'+base+'[value_label_he]" value="'+html(item.scope_value_he||item.value_label_he||'')+'"></label><label><span>Work type</span><select name="'+base+'[schedule_type]">'+scheduleOptions(item.schedule_type||'one_time',false)+'</select></label><label><span>Repeat frequency</span><select name="'+base+'[frequency]">'+frequencyOptions(item.frequency||'weekly',false)+'</select></label></div></article>';}
    function renderPackageWorkItems(host,items){host.innerHTML=(items||[]).map(packageWorkItemCard).join('')||'<p class="quote-package-empty">This service has no item templates yet.</p>';}
    function renumberWorkItems(){Array.prototype.forEach.call(workflowHost.children,function(card,index){card.querySelector('.service-work-item-number').textContent=index+1;});workflowEmpty.hidden=workflowHost.children.length>0;}function renderWorkItems(items){workflowHost.innerHTML='';workItemIndex=0;(items||[]).forEach(addWorkItem);renumberWorkItems();}
    document.getElementById('add-service-work-item').addEventListener('click',function(){addWorkItem({schedule_type:'one_time',frequency:'weekly'});});
    $('#quote-service-modal').on('show.bs.modal',function(e){var form=this.querySelector('form'),id=Number(e.relatedTarget.getAttribute('data-service-id')||0),source=(settingsData.services||[]).find(function(row){return Number(row.id)===id;}),data=source?JSON.parse(JSON.stringify(source)):{};form.reset();data.service_id=data.id||'';fill(form,data);form.querySelector('.modal-title').textContent=data.id?'Edit service & item templates':'Add service';if(!data.id){form.elements.active.checked=true;form.elements.taxable.checked=true;form.elements.quote_enabled.checked=true;}renderWorkItems(data.work_items||[]);});
    $('#quote-package-modal').on('show.bs.modal',function(e){var form=this.querySelector('form'),button=e.relatedTarget,raw=button.getAttribute('data-package'),data=raw?JSON.parse(raw):{},type=button.getAttribute('data-package-type')||data.package_type||'quote_setup',typeName=type==='support_contract'?'support contract':'setup';form.reset();var typeInput=form.elements.package_type;if(!typeInput){typeInput=document.createElement('input');typeInput.type='hidden';typeInput.name='package_type';form.appendChild(typeInput);}typeInput.value=type;data.package_id=data.id||'';fill(form,data);typeInput.value=type;form.querySelector('.modal-title').textContent=(data.id?'Edit ':'Add ')+typeName+' package';if(!data.id){form.elements.active.checked=true;form.elements.display_order.value=99;}else{form.elements.active.checked=Number(data.active)===1;}});
    $('#quote-package-add-item-modal').on('show.bs.modal',function(e){var form=this.querySelector('form'),button=e.relatedTarget;form.reset();form.elements.package_id.value=button.getAttribute('data-package-id');form.querySelector('.modal-title').textContent='Add service to '+button.getAttribute('data-package-name');form.elements.included.checked=true;form.elements.sort_order.value=99;var select=form.elements.service_id;function applyService(){var option=select.options[select.selectedIndex],service=JSON.parse(option.getAttribute('data-service')||'{}');form.elements.unit_price.value=service.default_price||0;form.elements.description.value=service.description||'';form.elements.description_ar.value=service.description_ar||'';form.elements.description_he.value=service.description_he||'';renderPackageWorkItems(document.getElementById('package-add-work-items'),service.work_items||[]);}select.onchange=applyService;applyService();});
    $('#quote-package-item-modal').on('show.bs.modal',function(e){var data=JSON.parse(e.relatedTarget.getAttribute('data-item')),form=this.querySelector('form');data.package_item_id=data.id;form.reset();fill(form,data);renderPackageWorkItems(document.getElementById('package-edit-work-items'),data.work_items||[]);});
    $('#quote-plan-modal').on('show.bs.modal',function(e){var form=this.querySelector('form'),type=e.relatedTarget.getAttribute('data-type'),data=JSON.parse(e.relatedTarget.getAttribute('data-plan'));data.plan_id=data.id;data.plan_type=type;form.reset();fill(form,data);form.querySelector('.support-plan-fields').style.display=type==='support'?'contents':'none';form.querySelector('.membership-plan-fields').style.display=type==='membership'?'contents':'none';});
});
</script>
