<?php
$locale=(string)request()->query('lang',$quote['locale']??'en');if(!in_array($locale,['en','ar','he'],true)){$locale='en';}
$rtl=$locale!=='en';
$publicMode=$publicMode??false;
$loc=static function(array $row,string $field)use($locale):string{$key=$locale==='en'?$field:$field.'_'.$locale;return (string)($row[$key]??$row[$field]??'');};
$shareUrl=url('quote/share/'.$quote['share_token']).'?lang='.$locale;
$pdfUrl=$publicMode?route('quote.public.pdf',['token'=>$quote['share_token'],'lang'=>$locale]):agency_url('quote_pdf',['id'=>$quote['id'],'lang'=>$locale]);
$translations=[
    'en'=>['proposal_summary'=>'PROPOSAL SUMMARY','client_details'=>'CLIENT AND BUSINESS DETAILS','date'=>'Date','valid_until'=>'Valid until','package'=>'Setup package','currency'=>'Currency','one_time'=>'One-time setup services','one_time_help'=>'Services and deliverables provided once under the selected setup package.','technical'=>'Technical support','technical_help'=>'Coverage calculated from the one-time setup subtotal.','contract'=>'Support contract services','contract_help'=>'Ongoing monthly services included in the selected support package.','scope'=>'Scope & deliverables','list_rate'=>'List rate','adjustment'=>'Adjustment','final'=>'Final price','subtotal'=>'Section subtotal','plan'=>'Support plan','duration'=>'Duration','pricing_basis'=>'Pricing basis','calculated'=>'Calculated support','months'=>'months','not_selected'=>'Not selected','support_package'=>'Support package','monthly_rate'=>'Monthly rate','monthly_subtotal'=>'Monthly subtotal','contract_term'=>'Contract term','contract_value'=>'Contract value','total_before_tax'=>'Total before tax','grand_total'=>'Grand total','custom_price'=>'Custom price','recurring'=>'Recurring','one_time_item'=>'One time','prices_note'=>'Prices in CAD. Third-party costs are separate unless expressly included.'],
    'ar'=>['proposal_summary'=>'ملخص العرض','client_details'=>'بيانات العميل والشركة','date'=>'التاريخ','valid_until'=>'صالح حتى','package'=>'باقة الإعداد','currency'=>'العملة','one_time'=>'خدمات الإعداد لمرة واحدة','one_time_help'=>'الخدمات والتسليمات المقدمة مرة واحدة ضمن باقة الإعداد المختارة.','technical'=>'الدعم الفني','technical_help'=>'تغطية يتم احتسابها من مجموع الإعداد لمرة واحدة.','contract'=>'خدمات عقد الدعم','contract_help'=>'الخدمات الشهرية المستمرة المشمولة في باقة الدعم المختارة.','scope'=>'النطاق والتسليمات','list_rate'=>'سعر القائمة','adjustment'=>'التعديل','final'=>'السعر النهائي','subtotal'=>'مجموع القسم','plan'=>'خطة الدعم','duration'=>'المدة','pricing_basis'=>'أساس التسعير','calculated'=>'الدعم المحسوب','months'=>'أشهر','not_selected'=>'غير محدد','support_package'=>'باقة الدعم','monthly_rate'=>'السعر الشهري','monthly_subtotal'=>'الإجمالي الشهري','contract_term'=>'مدة العقد','contract_value'=>'قيمة العقد','total_before_tax'=>'المجموع قبل الضريبة','grand_total'=>'المجموع الكلي','custom_price'=>'سعر مخصص','recurring'=>'متكرر','one_time_item'=>'مرة واحدة','prices_note'=>'الأسعار بالدولار الكندي. تكاليف الأطراف الثالثة منفصلة ما لم يتم تضمينها صراحة.'],
    'he'=>['proposal_summary'=>'סיכום הצעה','client_details'=>'פרטי הלקוח והעסק','date'=>'תאריך','valid_until'=>'בתוקף עד','package'=>'חבילת הקמה','currency'=>'מטבע','one_time'=>'שירותי הקמה חד-פעמיים','one_time_help'=>'שירותים ותוצרים הנמסרים פעם אחת במסגרת חבילת ההקמה שנבחרה.','technical'=>'תמיכה טכנית','technical_help'=>'כיסוי המחושב מסכום ההקמה החד-פעמי.','contract'=>'שירותי חוזה תמיכה','contract_help'=>'שירותים חודשיים שוטפים הכלולים בחבילת התמיכה שנבחרה.','scope'=>'היקף ותוצרים','list_rate'=>'מחיר מחירון','adjustment'=>'התאמה','final'=>'מחיר סופי','subtotal'=>'סכום הסעיף','plan'=>'תוכנית תמיכה','duration'=>'משך','pricing_basis'=>'בסיס תמחור','calculated'=>'תמיכה מחושבת','months'=>'חודשים','not_selected'=>'לא נבחר','support_package'=>'חבילת תמיכה','monthly_rate'=>'מחיר חודשי','monthly_subtotal'=>'סכום חודשי','contract_term'=>'תקופת החוזה','contract_value'=>'שווי החוזה','total_before_tax'=>'סכום לפני מס','grand_total'=>'סה״כ','custom_price'=>'מחיר מותאם','recurring'=>'חוזר','one_time_item'=>'חד-פעמי','prices_note'=>'המחירים בדולר קנדי. עלויות צד שלישי נפרדות אלא אם נכללו במפורש.'],
];
$text=$translations[$locale];
$setupItems=array_values(array_filter($quote['items'],static fn(array $item):bool=>in_array((string)($item['item_type']??'service'),['','service'],true)));
$technicalItems=array_values(array_filter($quote['items'],static fn(array $item):bool=>(string)($item['item_type']??'')==='support'));
$contractItems=array_values(array_filter($quote['items'],static fn(array $item):bool=>in_array((string)($item['item_type']??''),['support_contract','membership'],true)));
$technicalSubtotal=(float)($quote['support_amount']??array_sum(array_column($technicalItems,'total')));
$contractSubtotal=(float)($quote['membership_amount']??array_sum(array_column($contractItems,'total')));
$setupSubtotal=max(0,round((float)$quote['subtotal']-$technicalSubtotal-$contractSubtotal,2));
$contractDuration=max(0,(int)($quote['membership_duration_months']??0));
$contractMonthly=(float)($quote['membership_monthly_price']??0);
$supportDuration=max(0,(int)($quote['support_duration_months']??0));
$supportRate=(float)($quote['support_rate_percent']??0);
$supportCycles=$supportDuration>0?round($supportDuration/3,2):0;
$supportPackageName=$loc($quote,'support_package_name')?:((string)($quote['membership_name']??'')?:$text['not_selected']);
$adjustment=static function(array $item,bool $contract=false)use($text):string{
    $discount=(float)($item['discount_percent']??0);
    $quantity=$contract?max(1,(int)($item['quantity']??1)):1;
    $final=(float)($item['total']??0)/$quantity;
    $list=(float)($item['unit_price']??0);
    if($discount>0){return '-'.rtrim(rtrim(number_format($discount,2),'0'),'.').'%';}
    if(abs($list-$final)>.009){return $text['custom_price'];}
    return '—';
};
?>
<?php if(!$publicMode): ?>
<div class="quote-page-heading no-print"><div><span class="eyebrow">PROPOSAL <?= e($quote['proposal_number']) ?></span><h1><?= e($quote['business_name']) ?></h1><p>Revision <?= (int)$quote['revision'] ?> · Sent <?= (int)$quote['sent_count'] ?> times · <?= e(ucfirst($quote['status'])) ?></p></div><div class="quote-heading-actions"><a class="btn btn-outline-secondary" href="<?= e(agency_url('saved_quotes')) ?>"><i class="fal fa-arrow-left"></i> Saved quotes</a><?php if(($quote['status']??'draft')!=='accepted'): ?><a class="btn btn-outline-secondary" href="<?= e(agency_url('quote_studio',['id'=>$quote['id']])) ?>"><i class="fal fa-pencil"></i> Edit</a><?php else: ?><span class="btn btn-outline-secondary disabled"><i class="fal fa-lock"></i> Locked</span><?php endif; ?><a class="btn btn-primary" href="<?= e($pdfUrl) ?>" target="_blank" rel="noopener"><i class="fal fa-file-pdf"></i> Open PDF</a></div></div>
<?php endif; ?>
<div class="quote-language-row no-print"><strong><?= $publicMode?'Language':'Client language' ?></strong><?php foreach($locales as $code=>$language): ?><?php $languageUrl=$publicMode?route('quote.public',['token'=>$quote['share_token'],'lang'=>$code]):agency_url('quote_view',['id'=>$quote['id'],'lang'=>$code]); ?><a class="<?= $locale===$code?'active':'' ?>" href="<?= e($languageUrl) ?>"><?= e($language['label']) ?></a><?php endforeach; ?><?php if(!$publicMode): ?><label><span>Share link</span><input readonly value="<?= e($shareUrl) ?>" onclick="this.select()"></label><?php endif; ?><a class="btn btn-outline-secondary ml-auto" href="<?= e($pdfUrl) ?>" target="_blank" rel="noopener"><i class="fal fa-file-pdf"></i> Open PDF</a></div>
<article class="client-proposal client-proposal--detailed" dir="<?= $rtl?'rtl':'ltr' ?>">
    <header><div class="client-proposal-brand"><img src="<?= e(asset('img/360-logo-final-exact.png')) ?>" alt="360 Creative Agency"><strong>360 Creative Agency</strong></div><div><span><?= e($text['proposal_summary']) ?></span><strong><?= e($quote['proposal_number']) ?></strong></div></header>
    <section class="client-proposal-meta"><div><small><?= e($text['client_details']) ?></small><h2><?= e($quote['business_name']) ?></h2><p><?= e($quote['contact_name']) ?> · <?= e($quote['contact_email']) ?></p><?php if($quote['website']): ?><p><?= e($quote['website']) ?></p><?php endif; ?></div><dl><div><dt><?= e($text['date']) ?></dt><dd><?= e(date('Y-m-d',strtotime($quote['created_at']))) ?></dd></div><div><dt><?= e($text['valid_until']) ?></dt><dd><?= e($quote['valid_until']) ?></dd></div><div><dt><?= e($text['package']) ?></dt><dd><?= e($loc($quote,'package_name')?:strtoupper((string)$quote['selected_tier'])) ?></dd></div><div><dt><?= e($text['currency']) ?></dt><dd>CAD · Canadian Dollar</dd></div></dl></section>
    <section class="client-proposal-breakdown">
        <article class="proposal-cost-section proposal-cost-section--setup">
            <header><span>01</span><div><h3><?= e($text['one_time']) ?></h3><p><?= e($text['one_time_help']) ?></p></div><strong><?= money($setupSubtotal) ?></strong></header>
            <div class="proposal-cost-head"><span></span><span><?= e($text['scope']) ?></span><span><?= e($text['list_rate']) ?></span><span><?= e($text['adjustment']) ?></span><span><?= e($text['final']) ?></span></div>
            <?php foreach($setupItems as $index=>$item): ?>
                <div class="proposal-cost-row"><span><?= $index+1 ?></span><div><strong><?= e($loc($item,'title')) ?></strong><small><?= e($loc($item,'description')) ?></small><?php if(!empty($item['work_items'])): ?><ul class="client-proposal-work-items"><?php foreach($item['work_items'] as $workItem): ?><?php $scope=$loc($workItem,'scope_value');$schedule=$workItem['schedule_type']==='recurring'?$text['recurring'].' · '.ucfirst((string)($workItem['frequency']??'weekly')):$text['one_time_item']; ?><li><i class="fal fa-check-circle"></i><span><b><?= e($loc($workItem,'title')) ?></b><?php if($scope): ?><small><?= e($scope) ?></small><?php endif; ?></span><em><?= e($schedule) ?></em></li><?php endforeach; ?></ul><?php endif; ?></div><span><small><?= e($text['list_rate']) ?></small><b><?= money($item['unit_price']) ?></b></span><span><small><?= e($text['adjustment']) ?></small><b><?= e($adjustment($item)) ?></b></span><span class="proposal-line-total"><small><?= e($text['final']) ?></small><b><?= money($item['total']) ?></b></span></div>
            <?php endforeach; ?>
            <footer><span><?= e($text['subtotal']) ?></span><b><?= money($setupSubtotal) ?></b></footer>
        </article>

        <article class="proposal-cost-section proposal-cost-section--technical">
            <header><span>02</span><div><h3><?= e($text['technical']) ?></h3><p><?= e($text['technical_help']) ?></p></div><strong><?= money($technicalSubtotal) ?></strong></header>
            <div class="proposal-support-summary"><div><small><?= e($text['plan']) ?></small><strong><?= e((string)($quote['support_name']??'')?:$text['not_selected']) ?></strong><p><?= e($loc($technicalItems[0]??[],'description')) ?></p></div><div><small><?= e($text['duration']) ?></small><strong><?= $supportDuration>0?e($supportDuration.' '.$text['months']):'—' ?></strong></div><div><small><?= e($text['pricing_basis']) ?></small><strong><?= $technicalSubtotal>0?e(money($setupSubtotal).' × '.rtrim(rtrim(number_format($supportRate,2),'0'),'.').'% × '.$supportCycles):'—' ?></strong></div><div class="proposal-support-total"><small><?= e($text['calculated']) ?></small><strong><?= money($technicalSubtotal) ?></strong></div></div>
        </article>

        <article class="proposal-cost-section proposal-cost-section--contract">
            <header><span>03</span><div><h3><?= e($text['contract']) ?></h3><p><?= e($text['contract_help']) ?></p></div><strong><?= money($contractSubtotal) ?></strong></header>
            <div class="proposal-contract-meta"><div><small><?= e($text['support_package']) ?></small><strong><?= e($supportPackageName) ?></strong></div><div><small><?= e($text['monthly_subtotal']) ?></small><strong><?= money($contractMonthly) ?></strong></div><div><small><?= e($text['contract_term']) ?></small><strong><?= $contractDuration>0?e($contractDuration.' '.$text['months']):'—' ?></strong></div><div><small><?= e($text['contract_value']) ?></small><strong><?= money($contractSubtotal) ?></strong></div></div>
            <?php if($contractItems): ?><div class="proposal-cost-head proposal-cost-head--contract"><span></span><span><?= e($text['scope']) ?></span><span><?= e($text['list_rate']) ?></span><span><?= e($text['adjustment']) ?></span><span><?= e($text['monthly_rate']) ?></span><span><?= e($text['contract_value']) ?></span></div><?php endif; ?>
            <?php foreach($contractItems as $index=>$item): ?><?php $quantity=max(1,(int)($item['quantity']??($contractDuration?:1)));$monthlyFinal=(float)$item['total']/$quantity; ?>
                <div class="proposal-cost-row proposal-cost-row--contract"><span><?= $index+1 ?></span><div><strong><?= e($loc($item,'title')) ?></strong><small><?= e($loc($item,'description')) ?></small><?php if(!empty($item['work_items'])): ?><ul class="client-proposal-work-items"><?php foreach($item['work_items'] as $workItem): ?><?php $scope=$loc($workItem,'scope_value');$schedule=$workItem['schedule_type']==='recurring'?$text['recurring'].' · '.ucfirst((string)($workItem['frequency']??'weekly')):$text['one_time_item']; ?><li><i class="fal fa-check-circle"></i><span><b><?= e($loc($workItem,'title')) ?></b><?php if($scope): ?><small><?= e($scope) ?></small><?php endif; ?></span><em><?= e($schedule) ?></em></li><?php endforeach; ?></ul><?php endif; ?></div><span><small><?= e($text['list_rate']) ?></small><b><?= money($item['unit_price']) ?>/mo</b></span><span><small><?= e($text['adjustment']) ?></small><b><?= e($adjustment($item,true)) ?></b></span><span><small><?= e($text['monthly_rate']) ?></small><b><?= money($monthlyFinal) ?></b></span><span class="proposal-line-total"><small><?= e($text['contract_value']) ?></small><b><?= money($item['total']) ?></b></span></div>
            <?php endforeach; ?>
            <?php if(!$contractItems): ?><div class="proposal-empty-state"><?= e($text['not_selected']) ?></div><?php endif; ?>
            <footer><span><?= e($text['monthly_subtotal']) ?> <?= money($contractMonthly) ?> × <?= (int)$contractDuration ?> <?= e($text['months']) ?></span><b><?= money($contractSubtotal) ?></b></footer>
        </article>
    </section>
    <section class="client-proposal-total client-proposal-total--detailed"><div><span><?= e($text['one_time']) ?></span><b><?= money($setupSubtotal) ?></b></div><div><span><?= e($text['technical']) ?></span><b><?= money($technicalSubtotal) ?></b></div><div><span><?= e($text['contract']) ?><small><?= $contractDuration>0?e(money($contractMonthly).'/mo × '.$contractDuration.' '.$text['months']):'' ?></small></span><b><?= money($contractSubtotal) ?></b></div><div class="proposal-total-divider"><span><?= e($text['total_before_tax']) ?></span><b><?= money($quote['subtotal']) ?></b></div><div><span>HST <?= e(rtrim(rtrim(number_format((float)$quote['tax_percent'],2),'0'),'.')) ?>%</span><b><?= money($quote['tax']) ?></b></div><div class="grand"><span><?= e($text['grand_total']) ?></span><b><?= money($quote['total']) ?></b></div></section>
    <footer><div><strong>360 Creative Agency</strong><span><?= e($company['phone']) ?></span><span><?= e($company['email']) ?></span><span><?= e($company['website']) ?></span></div><div><span><?= e($company['address']) ?></span><span><?= e($text['prices_note']) ?></span></div></footer>
</article>
<?php if(!$publicMode): ?><section class="quote-delivery-card no-print"><div><h3>Send or resend this quote</h3><p>Every send is recorded. The client can open the same secure link in English, Arabic, or Hebrew.</p></div><form method="post" action="<?= e(agency_url('quote_view',['id'=>$quote['id']])) ?>" id="quote-delivery-form">@csrf<input type="hidden" name="action" value="record_quote_delivery"><input type="hidden" name="proposal_id" value="<?= (int)$quote['id'] ?>"><input type="hidden" name="locale" value="<?= e($locale) ?>"><input type="email" required name="recipient_email" value="<?= e($quote['contact_email']) ?>"><button class="btn btn-primary"><i class="fal fa-paper-plane"></i> Prepare email &amp; record send</button></form><?php if($quote['deliveries']): ?><div class="delivery-history"><?php foreach($quote['deliveries'] as $delivery): ?><span><i class="fal fa-check-circle"></i><?= e($delivery['recipient_email']) ?> · <?= e(strtoupper($delivery['locale'])) ?> · <?= e(date('M j, Y g:i A',strtotime($delivery['sent_at']))) ?></span><?php endforeach; ?></div><?php endif; ?></section>
<script>document.getElementById('quote-delivery-form').addEventListener('submit',function(){var email=this.elements.recipient_email.value;var subject=<?= json_encode('Proposal '.$quote['proposal_number'].' from 360 Creative Agency') ?>;var body=<?= json_encode("Hello ".$quote['contact_name'].",\n\nPlease review your proposal here:\n".$shareUrl."\n\nThank you,\n360 Creative Agency") ?>;window.open('mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body));});</script><?php endif; ?>
