<?php
$salesTotal=array_sum(array_column($reports['sales'],'value'));$weighted=array_sum(array_column($reports['sales'],'weighted'));
$revenue=array_sum(array_column($reports['profitability'],'revenue'));$cost=array_sum(array_column($reports['profitability'],'actual_cost'));$profit=$revenue-$cost;
?>
<div class="page-title-wrap"><div><span class="eyebrow">MANAGEMENT INTELLIGENCE</span><h1>Agency Reports</h1><p>Revenue, pipeline, utilization, and profitability from live operational data.</p></div><button class="btn btn-outline-secondary" data-print><i class="fal fa-print mr-1"></i> Export report</button></div>
<section class="panel report-highlight mb-4"><div class="panel-container show"><div class="panel-content"><div class="row">
<div class="col-md-3"><small class="text-uppercase opacity-60">Pipeline</small><div class="fs-xxl font-weight-bold"><?= e(money($salesTotal)) ?></div></div><div class="col-md-3"><small class="text-uppercase opacity-60">Weighted forecast</small><div class="fs-xxl font-weight-bold"><?= e(money($weighted)) ?></div></div><div class="col-md-3"><small class="text-uppercase opacity-60">Project value</small><div class="fs-xxl font-weight-bold"><?= e(money($revenue)) ?></div></div><div class="col-md-3"><small class="text-uppercase opacity-60">Gross margin</small><div class="fs-xxl font-weight-bold"><?= e(number_format($revenue?($profit/$revenue*100):0,1)) ?>%</div></div>
</div></div></div></section>

<div class="row"><div class="col-xl-6"><section class="panel"><div class="panel-hdr"><h2>Sales funnel</h2></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0 report-table"><thead><tr><th>Stage</th><th>Deals</th><th>Value</th><th>Weighted</th></tr></thead><tbody><?php foreach($reports['sales'] as $row): ?><tr><td><strong><?= e($row['stage']) ?></strong></td><td><?= (int)$row['deals'] ?></td><td><?= e(money($row['value'])) ?></td><td><?= e(money($row['weighted'])) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><td>Total</td><td><?= array_sum(array_column($reports['sales'],'deals')) ?></td><td><?= e(money($salesTotal)) ?></td><td><?= e(money($weighted)) ?></td></tr></tfoot></table></div></div></section></div>
<div class="col-xl-6"><section class="panel"><div class="panel-hdr"><h2>Client economics</h2></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Client</th><th>Package</th><th>MRR</th><th>Invoiced</th><th>Collected</th><th>Health</th></tr></thead><tbody><?php foreach($reports['clients'] as $row): ?><tr><td><strong><?= e($row['name']) ?></strong></td><td><?= e($row['package_name'] ?: '—') ?></td><td><?= e(money($row['monthly_price'])) ?></td><td><?= e(money($row['invoiced'])) ?></td><td><?= e(money($row['collected'])) ?></td><td><i class="health-dot health-<?= e($row['health']) ?>"></i><?= e(ucwords(str_replace('_',' ',$row['health']))) ?></td></tr><?php endforeach; ?></tbody></table></div></div></section></div></div>

<div class="row mt-3"><div class="col-xl-7"><section class="panel"><div class="panel-hdr"><h2>Project profitability</h2><div class="panel-toolbar"><span class="badge badge-soft-success">Internal only</span></div></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Project</th><th>Client</th><th>Revenue</th><th>Actual cost</th><th>Gross profit</th><th>Margin</th></tr></thead><tbody><?php foreach($reports['profitability'] as $row): ?><tr><td><strong><?= e($row['project_name']) ?></strong></td><td><?= e($row['business_name']) ?></td><td><?= e(money($row['revenue'])) ?></td><td><?= e(money($row['actual_cost'])) ?></td><td><?= e(money($row['gross_profit'])) ?></td><td><span class="badge badge-soft-<?= $row['margin']>=40?'success':'warning' ?>"><?= e(number_format($row['margin'],1)) ?>%</span></td></tr><?php endforeach; ?></tbody></table></div></div></section></div>
<div class="col-xl-5"><section class="panel"><div class="panel-hdr"><h2>Team utilization</h2></div><div class="panel-container show"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Employee</th><th>Hours</th><th>Cost</th><th>Open tasks</th></tr></thead><tbody><?php foreach($reports['team'] as $row): ?><tr><td><strong><?= e($row['name']) ?></strong><small class="d-block text-muted"><?= e($row['department']) ?></small></td><td><?= e(number_format($row['hours'],1)) ?>h</td><td><?= e(money($row['internal_cost'])) ?></td><td><?= (int)$row['open_tasks'] ?></td></tr><?php endforeach; ?></tbody></table></div></div></section></div></div>
