<div class="quote-page-heading">
    <div><span class="eyebrow">QUOTE &amp; ONBOARDING</span><h1>Saved Quotes</h1><p>Draft, revise, resend, and convert proposals without recreating client information.</p></div>
    <a class="btn btn-primary" href="<?= e(agency_url('quote_studio')) ?>"><i class="fal fa-plus mr-1"></i> New quote</a>
</div>
<section class="quote-list-card">
    <form class="quote-list-filters" method="get" action="<?= e(url('saved_quotes')) ?>">
        <label><i class="fal fa-search"></i><input name="q" value="<?= e($filters['q']??'') ?>" placeholder="Search quote, business, contact, or email"></label>
        <select name="status"><option value="">All statuses</option><?php foreach(['draft','sent','accepted','declined','expired'] as $status): ?><option value="<?= e($status) ?>" <?= ($filters['status']??'')===$status?'selected':'' ?>><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select>
        <button class="btn btn-primary" type="submit">Apply</button><a class="btn btn-outline-secondary" href="<?= e(agency_url('saved_quotes')) ?>">Clear</a>
    </form>
    <div class="table-responsive"><table class="quote-list-table"><thead><tr><th>Quote</th><th>Client / business</th><th>Package</th><th>Total</th><th>Status</th><th>Deliveries</th><th>Updated</th><th class="text-right">Actions</th></tr></thead><tbody>
    <?php if(!$quotes): ?><tr><td colspan="8"><div class="quote-empty"><i class="fal fa-file-invoice-dollar"></i><strong>No saved quotes yet</strong><span>Start the guided journey to create the first one.</span></div></td></tr><?php endif; ?>
    <?php foreach($quotes as $quote): ?>
        <tr><td><a class="quote-number" href="<?= e(agency_url('quote_view',['id'=>$quote['id']])) ?>"><?= e($quote['proposal_number']) ?></a><small>Revision <?= (int)$quote['revision'] ?></small></td><td><strong><?= e($quote['business_name']) ?></strong><small><?= e($quote['contact_name'].' · '.$quote['contact_email']) ?></small></td><td><span class="quote-tier-badge"><?= e(strtoupper($quote['package_tier']??$quote['selected_tier']??'')) ?></span><small><?= e($quote['package_name']??'Custom') ?></small></td><td><strong><?= money($quote['total']) ?></strong><small><?= e($quote['currency']) ?></small></td><td><span class="badge badge-<?= $quote['status']==='accepted'?'success':($quote['status']==='sent'?'warning':'secondary') ?>"><?= e(ucfirst($quote['status'])) ?></span></td><td><strong><?= (int)$quote['sent_count'] ?></strong><small><?= (int)$quote['delivery_count'] ?> records</small></td><td><?= e(date('M j, Y',strtotime($quote['updated_at']?:$quote['created_at']))) ?></td><td><div class="quote-row-actions"><a href="<?= e(agency_url('quote_view',['id'=>$quote['id']])) ?>" title="View"><i class="fal fa-eye"></i></a><a href="<?= e(agency_url('quote_studio',['id'=>$quote['id']])) ?>" title="Edit"><i class="fal fa-pencil"></i></a><form method="post" action="<?= e(agency_url('saved_quotes')) ?>">@csrf<input type="hidden" name="action" value="duplicate_quote"><input type="hidden" name="proposal_id" value="<?= (int)$quote['id'] ?>"><button title="Create revision"><i class="fal fa-copy"></i></button></form><?php if(empty($quote['client_id'])): ?><form method="post" action="<?= e(agency_url('saved_quotes')) ?>">@csrf<input type="hidden" name="action" value="onboard_quote"><input type="hidden" name="proposal_id" value="<?= (int)$quote['id'] ?>"><button title="Accept and onboard"><i class="fal fa-user-check"></i></button></form><?php endif; ?></div></td></tr>
    <?php endforeach; ?>
    </tbody></table></div>
</section>
